"""
🌐 Flask API Server — Your Trained Model
============================================
Auto-generated by DataVision AI

Model         : RandomForest
Target Column : price_range
Task Type     : classification
Features      : 20 columns

Usage:
    python api_server.py
    python api_server.py --port 8080
    
Endpoints:
    POST /predict    — Make a prediction (JSON body with your feature names)
    GET  /health     — Health check
    GET  /model-info — Model metadata and expected features
"""

import os
import json
import re
import pickle
import argparse
import numpy as np
import pandas as pd
from flask import Flask, request, jsonify
from sklearn.preprocessing import LabelEncoder, RobustScaler

app = Flask(__name__)

MODEL_STATE = None
FEATURE_ENGINEER = None
FEATURE_COLUMNS = ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen', 'wifi']
TARGET_COLUMN = 'price_range'
BEST_MODE = 'traditional'  # Which mode won during AutoML

# YOUR original column names with types and ranges (what you input)
RAW_FEATURE_INFO = {
    "battery_power": {"type": "numeric", "min": 510.0, "max": 1987.0, "default": 1238.51},
    "blue": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.49},
    "clock_speed": {"type": "numeric", "min": 0.5, "max": 3.0, "default": 1.52},
    "dual_sim": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.51},
    "fc": {"type": "numeric", "min": 0.0, "max": 16.0, "default": 4.29},
    "four_g": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.52},
    "int_memory": {"type": "numeric", "min": 2.0, "max": 64.0, "default": 32.05},
    "m_dep": {"type": "numeric", "min": 0.1, "max": 1.0, "default": 0.50},
    "mobile_wt": {"type": "numeric", "min": 80.0, "max": 199.0, "default": 140.24},
    "n_cores": {"type": "numeric", "min": 1.0, "max": 8.0, "default": 4.52},
    "pc": {"type": "numeric", "min": 0.0, "max": 20.0, "default": 9.92},
    "px_height": {"type": "numeric", "min": 15.0, "max": 1791.01, "default": 644.46},
    "ram": {"type": "numeric", "min": 296.99, "max": 3958.01, "default": 2124.26},
    "sc_h": {"type": "numeric", "min": 5.0, "max": 19.0, "default": 12.31},
    "sc_w": {"type": "numeric", "min": 0.0, "max": 17.0, "default": 5.76},
    "three_g": {"type": "numeric", "min": 1.0, "max": 1.0, "default": 1.00},
    "touch_screen": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.50},
    "wifi": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.51},
}


# =============================================================================
# Standalone Feature Engineer — exact DataVision preprocessing
# =============================================================================
class StandaloneFeatureEngineer:
    def __init__(self, state):
        self.transformers = state.get('transformers', {})
        self.encoders = state.get('encoders', {})
        self.feature_names = state.get('feature_names', [])
        self.original_columns = state.get('original_columns', [])
        self.selected_feature_indices = state.get('selected_feature_indices', None)
        self.is_fitted = state.get('is_fitted', True)
        self.stopwords = set("i me my myself we our ours ourselves you your yours yourself yourselves he him his himself she her hers herself it its itself they them their theirs themselves what which who whom this that these those am is are was were be been being have has had having do does did doing a an the and but if or because as until while of at by for with about against between through during before after above below to from up down in out on off over under again further then once here there when where why how all both each few more most other some such no nor not only own same so than too very s t can will just don should now d ll m o re ve y ain aren couldn didn doesn hadn hasn haven isn ma mightn mustn needn shan shouldn wasn weren won wouldn".split())
        self.positive_words = set("good great excellent amazing wonderful fantastic brilliant outstanding superb love best perfect beautiful awesome incredible impressive magnificent exceptional fabulous terrific marvelous stellar remarkable extraordinary delightful gorgeous splendid spectacular phenomenal exquisite lovely charming pleasant nice fine happy joy enjoy satisfied pleased glad cheerful excited thrilled".split())
        self.negative_words = set("bad terrible horrible awful worst poor disappointing disgusting pathetic useless dreadful atrocious appalling abysmal mediocre inferior unpleasant nasty vile wretched miserable lousy horrendous hideous ghastly hideous deplorable lamentable pitiful woeful tragic sad angry frustrated annoyed irritated disappointed upset unhappy distressed sorrowful gloomy depressed".split())

    def _clean_text(self, text):
        text = str(text).lower()
        text = re.sub(r'<[^>]+>', ' ', text)
        text = re.sub(r'http\S+', ' ', text)
        text = re.sub(r'[^a-z0-9\s]', ' ', text)
        text = ' '.join(w for w in text.split() if w not in self.stopwords and len(w) > 1)
        return text if text.strip() else 'empty'

    def _text_statistics(self, text):
        text = str(text)
        words = text.split()
        wl = [len(w) for w in words] if words else [0]
        return [len(text), len(words), np.mean(wl), np.std(wl), max(wl) if wl else 0,
                len(set(words)) / max(len(words), 1), text.count('!'), text.count('?'),
                sum(1 for c in text if c.isupper()) / max(len(text), 1),
                len([w for w in words if len(w) > 6]) / max(len(words), 1)]

    def _sentiment_score(self, text):
        words = set(str(text).lower().split())
        pos = len(words & self.positive_words)
        neg = len(words & self.negative_words)
        total = max(pos + neg, 1)
        return [pos / total, neg / total, (pos - neg) / total, total]

    def transform(self, df):
        df = df.copy()
        cols = df.columns.tolist()
        seen = {}
        new_cols = []
        for col in cols:
            if col in seen:
                seen[col] += 1
                new_cols.append(f"{col}_{seen[col]}")
            else:
                seen[col] = 0
                new_cols.append(col)
        df.columns = new_cols
        feature_parts = []

        if 'numeric_cols' in self.transformers:
            numeric_cols = self.transformers['numeric_cols']
            for col in numeric_cols:
                if col not in df.columns:
                    df[col] = 0
            try:
                numeric_data = df[numeric_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
                scaler = self.transformers['numeric_scaler']
                numeric_scaled = scaler.transform(numeric_data)
                numeric_scaled = np.nan_to_num(numeric_scaled, nan=0.0, posinf=0.0, neginf=0.0)
                feature_parts.append(numeric_scaled)
                if 2 <= len(numeric_cols) <= 10:
                    interactions = []
                    for i in range(min(len(numeric_cols), 4)):
                        interactions.append((numeric_scaled[:, i] ** 2).reshape(-1, 1))
                    for i in range(min(len(numeric_cols), 4)):
                        for j in range(i + 1, min(len(numeric_cols), 4)):
                            interactions.append((numeric_scaled[:, i] * numeric_scaled[:, j]).reshape(-1, 1))
                    if interactions:
                        feature_parts.append(np.hstack(interactions))
            except:
                feature_parts.append(np.zeros((len(df), len(numeric_cols))))

        for key, cols in self.transformers.items():
            if key.endswith('_onehot'):
                col_name = key.replace('_onehot', '')
                try:
                    if col_name in df.columns:
                        series = df[col_name].fillna('_MISSING_').astype(str).str.strip()
                        dummies = pd.get_dummies(series, prefix=col_name)
                        dummies = dummies.reindex(columns=cols, fill_value=0)
                        feature_parts.append(dummies.values.astype(float))
                    else:
                        feature_parts.append(np.zeros((len(df), len(cols))))
                except:
                    feature_parts.append(np.zeros((len(df), len(cols))))

        for col, le in self.encoders.items():
            try:
                if col in df.columns:
                    series = df[col].fillna('_MISSING_').astype(str).str.strip()
                    encoded = series.map(lambda s: le.transform([s])[0] if s in le.classes_ else -1)
                    feature_parts.append(encoded.values.reshape(-1, 1).astype(float))
                    freq_key = f'{col}_freq_map'
                    if freq_key in self.transformers:
                        freq_map = self.transformers[freq_key]
                        freq_encoded = series.map(lambda s: freq_map.get(s, 0.0)).values.astype(float)
                        feature_parts.append(freq_encoded.reshape(-1, 1))
                else:
                    feature_parts.append(np.zeros((len(df), 1)))
                    if f'{col}_freq_map' in self.transformers:
                        feature_parts.append(np.zeros((len(df), 1)))
            except:
                feature_parts.append(np.zeros((len(df), 1)))

        if 'cat_interactions' in self.transformers:
            for key, value in self.transformers['cat_interactions'].items():
                if key.endswith('_freq_map'):
                    continue
                try:
                    col1, col2, le = value
                    if col1 in df.columns and col2 in df.columns:
                        combined = df[col1].fillna('_NA_').astype(str) + "_X_" + df[col2].fillna('_NA_').astype(str)
                        encoded = combined.map(lambda s: le.transform([s])[0] if s in le.classes_ else -1)
                        feature_parts.append(encoded.values.reshape(-1, 1).astype(float))
                        fk = f"{key}_freq_map"
                        if fk in self.transformers['cat_interactions']:
                            fm = self.transformers['cat_interactions'][fk]
                            feature_parts.append(combined.map(lambda s: fm.get(s, 0.0)).values.reshape(-1, 1).astype(float))
                    else:
                        feature_parts.append(np.zeros((len(df), 1)))
                except:
                    pass

        if 'num_cat_aggs' in self.transformers:
            for key, mean_map in self.transformers['num_cat_aggs'].items():
                try:
                    parts = key.rsplit('_by_', 1)
                    if len(parts) == 2:
                        num_col, cat_col = parts[0], parts[1].rsplit('_mean', 1)[0]
                        if num_col in df.columns and cat_col in df.columns:
                            cat_s = df[cat_col].fillna('_NA_').astype(str)
                            dv = np.mean(list(mean_map.values())) if mean_map else 0
                            agg = cat_s.map(lambda s: mean_map.get(s, dv)).values.astype(float)
                            feature_parts.append(agg.reshape(-1, 1))
                            feature_parts.append((df[num_col].fillna(0).values - agg).reshape(-1, 1))
                        else:
                            feature_parts.extend([np.zeros((len(df), 1))] * 2)
                except:
                    pass

        for key, tfidf in self.transformers.items():
            if key.endswith('_tfidf'):
                col = key.replace('_tfidf', '')
                try:
                    if col in df.columns:
                        series = df[col].fillna('').astype(str)
                        cleaned = series.apply(self._clean_text)
                        tm = tfidf.transform(cleaned)
                        svd_key = f'{col}_svd'
                        feature_parts.append(self.transformers[svd_key].transform(tm) if svd_key in self.transformers else tm.toarray())
                        feature_parts.append(np.array([self._text_statistics(t) for t in series]))
                        feature_parts.append(np.array([self._sentiment_score(t) for t in series]))
                except:
                    pass

        if not feature_parts:
            return np.zeros((len(df), len(self.feature_names)))
        X = np.hstack(feature_parts)
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

        if 'variance_selector' in self.transformers:
            sel = self.transformers['variance_selector']
            try:
                if X.shape[1] == sel.n_features_in_:
                    X = sel.transform(X)
                elif self.selected_feature_indices is not None:
                    vi = [i for i in self.selected_feature_indices if i < X.shape[1]]
                    if vi:
                        X = X[:, vi]
            except:
                pass

        if 'pca' in self.transformers:
            try:
                pca = self.transformers['pca']
                if X.shape[1] == pca.n_features_in_:
                    X = pca.transform(X)
            except:
                pass

        if X.shape[1] != len(self.feature_names):
            if X.shape[1] < len(self.feature_names):
                X = np.hstack([X, np.zeros((len(df), len(self.feature_names) - X.shape[1]))])
            else:
                X = X[:, :len(self.feature_names)]
        return X

    def transform_single(self, data):
        for col in self.original_columns:
            if col not in data:
                data[col] = 0
        df = pd.DataFrame([data])
        X = self.transform(df)
        n = len(self.feature_names)
        if X.shape[1] < n:
            X = np.hstack([X, np.zeros((1, n - X.shape[1]))])
        elif X.shape[1] > n:
            X = X[:, :n]
        return X


def load_model():
    global MODEL_STATE, FEATURE_ENGINEER
    
    # If best mode is deep_learning, load DL first as primary
    if BEST_MODE == 'deep_learning':
        load_dl_model()
        if DL_STATE is not None:
            print(f"🧠 Primary mode: Deep Learning (BEST_MODE={BEST_MODE})")
            # Also try loading ML model as fallback
            for path in ['model.pkl', 'nlp_model.pkl']:
                if os.path.exists(path):
                    with open(path, 'rb') as f:
                        MODEL_STATE = pickle.load(f)
                    print(f"   Also loaded fallback: {path}")
                    break
            return True
    
    # Traditional/NLP: load ML model first
    for path in ['model.pkl', 'nlp_model.pkl']:
        if os.path.exists(path):
            with open(path, 'rb') as f:
                MODEL_STATE = pickle.load(f)
            print(f"✅ Loaded: {path} ({MODEL_STATE.get('model_name', 'Unknown')})")
            # Load feature engineer for exact preprocessing
            eng_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'feature_engineer.pkl')
            if os.path.exists(eng_path):
                try:
                    with open(eng_path, 'rb') as ef:
                        eng_state = pickle.load(ef)
                    FEATURE_ENGINEER = StandaloneFeatureEngineer(eng_state)
                    print(f"   Pipeline: feature_engineer.pkl ({len(FEATURE_ENGINEER.feature_names)} features)")
                except Exception as e:
                    print(f"   Warning: Could not load feature_engineer.pkl: {e}")
            break
    
    # Also load DL model if available
    load_dl_model()
    
    if MODEL_STATE is None and DL_STATE is None:
        print("❌ No model file found")
        return False
    return True


# =============================================================================
# Deep Learning Model Support (sklearn MLPClassifier/MLPRegressor)
# =============================================================================
DL_STATE = None

def load_dl_model():
    """Load the Deep Learning model if available."""
    global DL_STATE
    dl_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'deep_learning_model.pkl')
    if os.path.exists(dl_path):
        try:
            with open(dl_path, 'rb') as f:
                DL_STATE = pickle.load(f)
            print(f"✅ Loaded DL model: {DL_STATE.get('algorithm', 'MLP')}")
        except Exception as e:
            print(f"⚠️ Failed to load DL model: {e}")


def preprocess_dl_input(data):
    """Preprocess input for Deep Learning model using feature_metadata."""
    feature_metadata = DL_STATE.get('feature_metadata', [])
    feature_values = []
    
    # Process numeric features
    for meta in feature_metadata:
        if meta.get('type') == 'numeric':
            col = meta['name']
            if col in data:
                try:
                    feature_values.append(float(data[col]))
                except (ValueError, TypeError):
                    feature_values.append(meta.get('mean', 0))
            else:
                feature_values.append(meta.get('mean', 0))
    
    # Process categorical features (one-hot)
    for meta in feature_metadata:
        if meta.get('type') == 'categorical':
            col = meta['name']
            value = str(data.get(col, ''))
            options = meta.get('options', [])
            for opt in options:
                feature_values.append(1.0 if value == opt else 0.0)
            feature_values.append(1.0 if not value or value == 'nan' else 0.0)
    
    # Fallback
    if not feature_values and DL_STATE.get('feature_columns'):
        for col in DL_STATE['feature_columns']:
            if col in data:
                try:
                    feature_values.append(float(data[col]) if not isinstance(data[col], str) else 0)
                except:
                    feature_values.append(0)
            else:
                feature_values.append(0)
    
    X = np.array([feature_values])
    
    scaler = DL_STATE.get('scaler')
    if scaler and hasattr(scaler, 'n_features_in_'):
        expected = scaler.n_features_in_
        actual = X.shape[1]
        if actual < expected:
            X = np.hstack([X, np.zeros((1, expected - actual))])
        elif actual > expected:
            X = X[:, :expected]
    
    if scaler:
        X = scaler.transform(X)
    
    return X


def preprocess_input(data):
    """Preprocess raw input using the EXACT same pipeline as DataVision AutoML."""
    global FEATURE_ENGINEER
    
    # Use feature engineer (exact AutoML pipeline)
    if FEATURE_ENGINEER is not None:
        try:
            return FEATURE_ENGINEER.transform_single(data)
        except Exception as e:
            print(f"Warning: Feature engineer failed ({e}), using fallback")
    
    # Fallback: basic label-encode + scale
    feature_cols = MODEL_STATE.get('feature_columns', FEATURE_COLUMNS)
    label_encoders = MODEL_STATE.get('label_encoders', {})
    scaler = MODEL_STATE.get('scaler')
    
    row = {}
    for col in feature_cols:
        val = data.get(col, 0)
        if col in label_encoders:
            le = label_encoders[col]
            val_str = str(val)
            if val_str in le.classes_:
                val = le.transform([val_str])[0]
            else:
                val = 0
        else:
            try:
                val = float(val)
            except (ValueError, TypeError):
                val = 0
        row[col] = val
    
    X = pd.DataFrame([row], columns=feature_cols)
    if scaler:
        try:
            X = pd.DataFrame(scaler.transform(X), columns=feature_cols)
        except:
            pass
    return X


@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "model_loaded": MODEL_STATE is not None or DL_STATE is not None, "dl_model_loaded": DL_STATE is not None})


@app.route('/model-info', methods=['GET'])
def model_info():
    if MODEL_STATE is None and DL_STATE is None:
        return jsonify({"error": "No model loaded"}), 404
    
    info = {"best_mode": BEST_MODE}
    if BEST_MODE == 'deep_learning' and DL_STATE:
        info.update({
            "model_name": DL_STATE.get('algorithm', 'MLP Neural Network'),
            "task_type": DL_STATE.get('task_type', 'classification'),
            "target_column": TARGET_COLUMN,
            "input_features": list(RAW_FEATURE_INFO.keys()),
            "metrics": {k: float(v) if isinstance(v, (int, float)) else str(v) 
                        for k, v in DL_STATE.get('metrics', {}).items()},
        })
    elif MODEL_STATE:
        info.update({
            "model_name": MODEL_STATE.get('model_name', 'Unknown'),
            "task_type": MODEL_STATE.get('task_type', 'classification'),
            "target_column": TARGET_COLUMN,
            "input_features": list(RAW_FEATURE_INFO.keys()),
            "metrics": {k: float(v) if isinstance(v, (int, float)) else str(v) 
                        for k, v in MODEL_STATE.get('metrics', {}).items()},
        })
    if DL_STATE:
        info["dl_model"] = {
            "algorithm": DL_STATE.get('algorithm', 'MLP'),
            "task_type": DL_STATE.get('task_type', 'classification'),
            "metrics": {k: float(v) if isinstance(v, (int, float)) else str(v) 
                        for k, v in DL_STATE.get('metrics', {}).items()},
        }
    return jsonify(info)


@app.route('/predict', methods=['GET', 'POST'])
def predict():
    if MODEL_STATE is None and DL_STATE is None:
        return jsonify({"error": "No model loaded"}), 500
    
    # GET request: show web form for interactive prediction
    if request.method == 'GET':
        if BEST_MODE == 'deep_learning' and DL_STATE:
            model_name = DL_STATE.get('algorithm', 'MLP Neural Network')
            task_type_val = DL_STATE.get('task_type', 'classification')
            metrics = DL_STATE.get('metrics', {})
        elif MODEL_STATE:
            model_name = MODEL_STATE.get('model_name', 'Unknown')
            task_type_val = MODEL_STATE.get('task_type', 'classification')
            metrics = MODEL_STATE.get('metrics', {})
        else:
            model_name = 'Unknown'
            task_type_val = 'classification'
            metrics = {}
        
        # Build form from RAW features (original column names user knows)
        form_fields = ""
        for col, info in RAW_FEATURE_INFO.items():
            ftype = info.get("type", "numeric")
            if ftype == "categorical":
                options = info.get("options", [])
                opts_html = "".join('<option value="' + str(o) + '">' + str(o) + '</option>' for o in options[:20])
                form_fields += '<div style="margin:6px 0"><label style="display:inline-block;width:260px;font-weight:500">' + col + '</label><select name="' + col + '" style="padding:6px 10px;border:1px solid #d1d5db;border-radius:6px;width:214px">' + opts_html + '</select></div>' + chr(10)
            else:
                default_val = str(info.get("default", 0))
                mn = str(info.get("min", ""))
                mx = str(info.get("max", ""))
                placeholder = (mn + " - " + mx) if mn != "" else ""
                form_fields += '<div style="margin:6px 0"><label style="display:inline-block;width:260px;font-weight:500">' + col + '</label><input name="' + col + '" type="text" value="' + default_val + '" placeholder="' + placeholder + '" style="padding:6px 10px;border:1px solid #d1d5db;border-radius:6px;width:200px"></div>' + chr(10)
        
        metrics_html = ""
        for k, v in metrics.items():
            if isinstance(v, float):
                metrics_html += f"<li><b>{k}</b>: {v:.4f}</li>"
        
        html_tpl = '<!DOCTYPE html>'
        html_tpl += '<html><head><title>DataVision ML API</title>'
        html_tpl += '<style>'
        html_tpl += "body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; background: #f9fafb; color: #111827; }}"
        html_tpl += 'h1 {{ color: #4F46E5; }} h2 {{ color: #1f2937; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }}'
        html_tpl += '.card {{ background: white; border-radius: 12px; padding: 24px; margin: 16px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}'
        html_tpl += 'button {{ background: #4F46E5; color: white; border: none; padding: 12px 32px; border-radius: 8px; font-size: 16px; cursor: pointer; margin-top: 12px; }}'
        html_tpl += 'button:hover {{ background: #4338CA; }}'
        html_tpl += '#result {{ margin-top: 20px; padding: 16px; background: #f0fdf4; border-radius: 8px; display: none; }}'
        html_tpl += '</style></head><body>'
        html_tpl += '<h1>🚀 DataVision ML API</h1>'
        html_tpl += '<div class="card"><h2>Model Info</h2>'
        html_tpl += '<p>🏆 <b>Model:</b> ' + str(model_name) + ' | 🎯 <b>Target:</b> price_range | 📊 <b>Task:</b> ' + str(task_type_val) + ' | 📁 <b>Features:</b> ' + str(len(RAW_FEATURE_INFO)) + '</p>'
        html_tpl += '<ul>' + metrics_html + '</ul></div>'
        html_tpl += '<div class="card"><h2>🔮 Make a Prediction</h2>'
        html_tpl += '<form id="predForm">' + form_fields + '<button type="submit">Predict</button></form>'
        html_tpl += '<div id="result"></div></div>'
        html_tpl += '<div class="card"><h2>📡 API Usage</h2>'
        html_tpl += '<pre style="background:#1f2937;color:#e5e7eb;padding:16px;border-radius:8px;overflow-x:auto">'
        html_tpl += 'POST /predict\nContent-Type: application/json\n\n' + chr(123) + '"feature1": val, "feature2": val' + chr(125)
        html_tpl += '\n\nGET /health — Health check\nGET /model-info — Model metadata</pre></div>'
        html_tpl += '<script>'
        html_tpl += 'document.getElementById("predForm").onsubmit=function(e)' + chr(123)
        html_tpl += 'e.preventDefault();var fd=new FormData(this);var data=' + chr(123) + chr(125) + ';'
        html_tpl += 'fd.forEach(function(v,k)' + chr(123) + 'data[k]=isNaN(v)||v===""?v:parseFloat(v)' + chr(125) + ');'
        html_tpl += 'fetch("/predict",' + chr(123) + 'method:"POST",headers:' + chr(123) + '"Content-Type":"application/json"' + chr(125) + ',body:JSON.stringify(data)' + chr(125) + ')'
        html_tpl += '.then(function(r)' + chr(123) + 'return r.json()' + chr(125) + ')'
        html_tpl += '.then(function(j)' + chr(123)
        html_tpl += 'var h="<h3>🎯 Prediction: "+j.prediction+"</h3>";'
        html_tpl += 'if(j.confidence)h+="<p>📊 Confidence: "+(j.confidence*100).toFixed(1)+"%</p>";'
        html_tpl += 'if(j.probabilities)' + chr(123) + 'h+="<p>Probabilities:</p><ul>";'
        html_tpl += 'var ent=Object.entries(j.probabilities).sort(function(a,b)' + chr(123) + 'return b[1]-a[1]' + chr(125) + ');'
        html_tpl += 'for(var i=0;i<ent.length;i++)h+="<li><b>"+ent[i][0]+"</b>: "+(ent[i][1]*100).toFixed(1)+"%</li>";'
        html_tpl += 'h+="</ul>"' + chr(125)
        html_tpl += 'document.getElementById("result").innerHTML=h;document.getElementById("result").style.display="block"'
        html_tpl += chr(125) + ')' + chr(125) + ';'
        html_tpl += '</script></body></html>'
        return html_tpl
    
    # POST request: JSON API prediction
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "No JSON body. Send features as JSON.", "expected_features": list(RAW_FEATURE_INFO.keys())}), 400
        
        # Check if caller wants DL mode, or if BEST_MODE is deep_learning, or if only DL is available
        req_mode = data.pop('_mode', None)
        use_dl = (req_mode == 'dl') or (req_mode != 'ml' and BEST_MODE == 'deep_learning' and DL_STATE is not None) or (MODEL_STATE is None and DL_STATE is not None)
        
        if use_dl and DL_STATE:
            # Deep Learning prediction
            X = preprocess_dl_input(data)
            dl_model = DL_STATE['model']
            label_encoder = DL_STATE.get('label_encoder')
            task_type = DL_STATE.get('task_type', 'classification')
            classes = DL_STATE.get('classes', [])
            
            pred = dl_model.predict(X)[0]
            result = {"raw_prediction": int(pred) if isinstance(pred, (np.integer,)) else float(pred)}
            
            if 'classif' in task_type.lower() and label_encoder:
                try:
                    result['prediction'] = str(label_encoder.inverse_transform([int(pred)])[0])
                except:
                    result['prediction'] = str(pred)
            else:
                result['prediction'] = float(pred)
            
            if 'classif' in task_type.lower() and hasattr(dl_model, 'predict_proba'):
                try:
                    proba = dl_model.predict_proba(X)[0]
                    result['confidence'] = float(max(proba))
                    if classes:
                        result['probabilities'] = {
                            str(c): round(float(p), 4) for c, p in zip(classes, proba)
                        }
                except:
                    pass
            
            result['mode'] = 'deep_learning'
            return jsonify(result)
        
        # Traditional/NLP prediction
        model = MODEL_STATE['model']
        target_encoder = MODEL_STATE.get('target_encoder')
        task_type = MODEL_STATE.get('task_type', 'classification')
        
        X = preprocess_input(data)
        
        prediction = model.predict(X)[0]
        result = {"raw_prediction": int(prediction) if isinstance(prediction, (np.integer,)) else float(prediction)}
        
        if 'classif' in task_type.lower() and target_encoder:
            try:
                result['prediction'] = str(target_encoder.inverse_transform([int(prediction)])[0])
            except:
                result['prediction'] = str(prediction)
        else:
            result['prediction'] = float(prediction)
        
        if 'classif' in task_type.lower() and hasattr(model, 'predict_proba'):
            try:
                proba = model.predict_proba(X)[0]
                result['confidence'] = float(max(proba))
                if target_encoder:
                    result['probabilities'] = {
                        str(c): round(float(p), 4) for c, p in zip(target_encoder.classes_, proba)
                    }
            except:
                pass
        
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', type=int, default=5000)
    parser.add_argument('--host', type=str, default='0.0.0.0')
    args = parser.parse_args()
    
    if load_model():
        print(f"\n🌐 API Server on http://{args.host}:{args.port}")
        print(f"   POST /predict  — Send JSON with your feature values")
        print(f"   GET  /health   — Health check")
        print(f"   GET  /model-info — Your model details and expected features")
        app.run(host=args.host, port=args.port, debug=False)
