"""
🚀 Traditional ML Training Script — YOUR DataVision AutoML Results
=====================================================================
Auto-generated by DataVision AI

╔═══════════════════════════════════════════════════════════════════════╗
║  📦 model.pkl contains your ALREADY TRAINED model with the metrics   ║
║     you saw in the AutoML UI.                                         ║
║                                                                       ║
║  ▶ python evaluate.py    — See your EXACT AutoML results             ║
║  ▶ python predict.py     — Make predictions with your model          ║
║                                                                       ║
║  This script is for RETRAINING only. Results may differ slightly     ║
║  due to train/test random split, even with same hyperparameters.     ║
╚═══════════════════════════════════════════════════════════════════════╝

YOUR AUTOML TRAINING RESULTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏆 WINNING MODEL : RandomForest
🎯 Target        : price_range
📊 Task          : classification
📁 Features      : 20 columns

YOUR METRICS:
#   accuracy: 0.8925
#   f1: 0.8929
#   precision: 0.8937
#   recall: 0.8925
#   roc_auc: 0.9796

YOUR LEADERBOARD (what AutoML trained):
#   1. ?: 0.8925

FEATURE INFO:
#   battery_power: numeric (min=510.0, max=1987.0, mean=1238.513)
#   blue: numeric (min=0.0, max=1.0, mean=0.495)
#   clock_speed: numeric (min=0.5, max=3.0, mean=1.52225)
#   dual_sim: numeric (min=0.0, max=1.0, mean=0.5095)
#   fc: numeric (min=0.0, max=16.0, mean=4.294)
#   four_g: numeric (min=0.0, max=1.0, mean=0.5215)
#   int_memory: numeric (min=2.0, max=64.0, mean=32.0465)
#   m_dep: numeric (min=0.1, max=1.0, mean=0.50175)
#   mobile_wt: numeric (min=80.0, max=199.0, mean=140.2395)
#   n_cores: numeric (min=1.0, max=8.0, mean=4.5205)

Usage:
    # VERIFY YOUR AUTOML RESULTS:
    python evaluate.py                             # Shows exact AutoML metrics
    
    # MAKE PREDICTIONS:
    python predict.py --json '{"col1": value}'   # Your trained model
    
    # RETRAIN (if needed):
    python train_traditional.py                    # Train ONLY RandomForest
    python train_traditional.py --all              # Train ALL algorithms
"""

import os
import pickle
import argparse
import time
import warnings
import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from sklearn.model_selection import train_test_split, StratifiedKFold, KFold, cross_val_score
from sklearn.preprocessing import LabelEncoder, RobustScaler, StandardScaler
from sklearn.feature_selection import VarianceThreshold
from sklearn.impute import KNNImputer
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    r2_score, mean_absolute_error, mean_squared_error,
    classification_report, confusion_matrix
)
from sklearn.ensemble import (
    RandomForestClassifier, RandomForestRegressor,
    GradientBoostingClassifier, GradientBoostingRegressor,
    ExtraTreesClassifier, ExtraTreesRegressor,
    HistGradientBoostingClassifier, HistGradientBoostingRegressor,
    AdaBoostClassifier, AdaBoostRegressor,
    BaggingClassifier, BaggingRegressor,
)
from sklearn.linear_model import (
    LogisticRegression, Ridge, Lasso, ElasticNet,
    SGDClassifier, SGDRegressor, RidgeClassifier,
    PassiveAggressiveClassifier, PassiveAggressiveRegressor,
    BayesianRidge
)
from sklearn.svm import SVC, SVR
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

warnings.filterwarnings('ignore')

HAS_XGB = False
HAS_LGB = False
HAS_CB = False
HAS_SMOTE = False

try:
    import xgboost as xgb
    HAS_XGB = True
except ImportError:
    pass
try:
    import lightgbm as lgb
    HAS_LGB = True
except ImportError:
    pass
try:
    from catboost import CatBoostClassifier, CatBoostRegressor
    HAS_CB = True
except ImportError:
    pass
try:
    from imblearn.over_sampling import SMOTE
    HAS_SMOTE = True
except ImportError:
    pass

TARGET_COLUMN = 'price_range'
TASK_TYPE = 'classification'

# YOUR WINNING MODEL FROM AUTOML
BEST_MODEL_NAME = 'RandomForest'


# ============================================================================
# STEP 1: DATA CLEANING (mirrors ProductionDataCleaner.clean())
# ============================================================================

def clean_data(df):
    """
    Mirrors DataVision's ProductionDataCleaner pipeline:
    1. Remove useless columns (IDs, URLs, high-cardinality strings)
    2. Remove exact duplicates
    3. Strip whitespace, replace 'nan'/'None'/'' with NaN
    4. Smart type conversion (parse $, M/K units, commas)
    5. KNN imputation for numerics (median fallback)
    6. Mode fill for categoricals
    7. Replace inf/-inf with median
    8. Remove constant columns (nunique <= 1)
    9. IQR-based outlier capping (Q1-3*IQR to Q3+3*IQR, clipped to [1st, 99th] percentile)
    10. Final NaN fill to 0
    """
    print("\n🧹 Step 1: Data Cleaning (ProductionDataCleaner)")
    print("-" * 50)
    original_shape = df.shape
    
    # Remove useless columns
    id_patterns = ['unnamed', 'index', '_id', 'guid', 'uuid', 'url', 'link', 'href', 'path']
    cols_to_drop = []
    for col in df.columns:
        col_lower = col.lower().strip()
        if any(pat in col_lower for pat in id_patterns):
            if col != TARGET_COLUMN:
                cols_to_drop.append(col)
        elif df[col].dtype == 'object' and col != TARGET_COLUMN:
            unique_ratio = df[col].nunique() / max(len(df), 1)
            if unique_ratio > 0.9:
                cols_to_drop.append(col)
    if cols_to_drop:
        df = df.drop(columns=cols_to_drop, errors='ignore')
        print(f"   Dropped {len(cols_to_drop)} useless columns: {cols_to_drop[:5]}")
    
    # Remove exact duplicates
    before = len(df)
    df = df.drop_duplicates()
    if len(df) < before:
        print(f"   Removed {before - len(df)} duplicate rows")
    
    # Strip whitespace + replace string NaN variants
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].str.strip()
        df[col] = df[col].replace(
            ['nan', 'NaN', 'None', 'null', 'NULL', 'none', 'NA', 'N/A', ''],
            np.nan
        )
    
    # Smart type conversion (parse $, M/K, commas)
    for col in df.select_dtypes(include=['object']).columns:
        if col == TARGET_COLUMN:
            continue
        sample = df[col].dropna().head(20)
        if len(sample) == 0:
            continue
        converted = 0
        for val in sample:
            try:
                v = str(val).replace('$', '').replace(',', '').strip()
                if v.upper().endswith('M'):
                    float(v[:-1])
                elif v.upper().endswith('K'):
                    float(v[:-1])
                elif v.endswith('+'):
                    float(v[:-1])
                else:
                    float(v)
                converted += 1
            except:
                pass
        if converted / max(len(sample), 1) > 0.6:
            def parse_value(val):
                if pd.isna(val):
                    return np.nan
                v = str(val).replace('$', '').replace(',', '').strip()
                try:
                    if v.upper().endswith('M'):
                        return float(v[:-1]) * 1_000_000
                    elif v.upper().endswith('K'):
                        return float(v[:-1]) * 1_000
                    elif v.endswith('+'):
                        return float(v[:-1])
                    return float(v)
                except:
                    return np.nan
            df[col] = df[col].apply(parse_value)
            print(f"   Converted {col} to numeric (parsed special formats)")
    
    # KNN imputation for numeric columns
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if TARGET_COLUMN in numeric_cols:
        numeric_cols.remove(TARGET_COLUMN)
    if numeric_cols and df[numeric_cols].isna().any().any():
        try:
            imputer = KNNImputer(n_neighbors=5, weights='distance')
            df[numeric_cols] = imputer.fit_transform(df[numeric_cols])
            print(f"   KNN imputed {len(numeric_cols)} numeric columns")
        except:
            for col in numeric_cols:
                df[col] = df[col].fillna(df[col].median())
            print(f"   Median-filled {len(numeric_cols)} numeric columns (KNN fallback)")
    
    # Mode fill for categoricals
    for col in df.select_dtypes(include=['object', 'category']).columns:
        if col == TARGET_COLUMN:
            continue
        mode = df[col].mode()
        df[col] = df[col].fillna(mode.iloc[0] if len(mode) > 0 else '_MISSING_')
    
    # Replace inf/-inf with median
    for col in numeric_cols:
        if np.isinf(df[col]).any():
            med = df[col].replace([np.inf, -np.inf], np.nan).median()
            df[col] = df[col].replace([np.inf, -np.inf], med)
    
    # Remove constant columns
    const_cols = [col for col in df.columns if col != TARGET_COLUMN and df[col].nunique() <= 1]
    if const_cols:
        df = df.drop(columns=const_cols)
        print(f"   Removed {len(const_cols)} constant columns")
    
    # IQR-based outlier capping (same as DataVision)
    capped_count = 0
    for col in df.select_dtypes(include=[np.number]).columns:
        if col == TARGET_COLUMN:
            continue
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        p1 = df[col].quantile(0.01)
        p99 = df[col].quantile(0.99)
        lower = max(p1, Q1 - 3 * IQR)
        upper = min(p99, Q3 + 3 * IQR)
        before_clip = ((df[col] < lower) | (df[col] > upper)).sum()
        if before_clip > 0:
            df[col] = df[col].clip(lower=lower, upper=upper)
            capped_count += before_clip
    if capped_count:
        print(f"   Capped {capped_count} outlier values (IQR method)")
    
    # Final NaN fill
    for col in df.select_dtypes(include=[np.number]).columns:
        df[col] = df[col].fillna(0)
    
    print(f"   Clean: {original_shape} → {df.shape}")
    return df


# ============================================================================
# STEP 2: FEATURE ENGINEERING (mirrors ProductionFeatureEngineer)
# ============================================================================

def engineer_features(X, mode='fast'):
    """
    Mirrors DataVision's ProductionFeatureEngineer.fit_transform():
    1. Detect column types (numeric, categorical, text, datetime)
    2. Log-transform skewed numerics (skewness > 2)
    3. RobustScaler for numeric features
    4. Polynomial features (squared + interactions for top columns)
    5. Categorical: binary→LabelEncoder, low-card→one-hot, high-card→label+frequency
    6. VarianceThreshold (remove near-constant features, threshold=0.01)
    """
    print("\n🔧 Step 2: Feature Engineering (ProductionFeatureEngineer)")
    print("-" * 50)
    
    numeric_cols = X.select_dtypes(include=[np.number]).columns.tolist()
    categorical_cols = X.select_dtypes(include=['object', 'category']).columns.tolist()
    
    label_encoders = {}
    
    # --- Numeric feature engineering ---
    # Log transform skewed features (skewness > 2, non-negative only)
    log_transformed = []
    for col in numeric_cols:
        if (X[col] >= 0).all():
            skew = X[col].skew()
            if abs(skew) > 2:
                X[f'{col}_log'] = np.log1p(X[col])
                log_transformed.append(col)
    if log_transformed:
        print(f"   Log-transformed {len(log_transformed)} skewed features")
    
    # Scale with RobustScaler (same as DataVision)
    numeric_cols_updated = X.select_dtypes(include=[np.number]).columns.tolist()
    scaler = RobustScaler()
    if numeric_cols_updated:
        X[numeric_cols_updated] = scaler.fit_transform(X[numeric_cols_updated])
    
    # Polynomial features (top 4 numeric columns — squared + interactions)
    if 2 <= len(numeric_cols) <= 10:
        top_n = min(4, len(numeric_cols))
        top_cols = numeric_cols[:top_n]
        for col in top_cols:
            X[f'{col}_sq'] = X[col] ** 2
        for i in range(len(top_cols)):
            for j in range(i + 1, len(top_cols)):
                X[f'{top_cols[i]}_x_{top_cols[j]}'] = X[top_cols[i]] * X[top_cols[j]]
        print(f"   Added polynomial features for top {top_n} numeric columns")
    
    # --- Categorical feature engineering ---
    for col in categorical_cols:
        nuniq = X[col].nunique()
        if nuniq <= 2:
            # Binary: LabelEncoder
            le = LabelEncoder()
            X[col] = le.fit_transform(X[col].astype(str))
            label_encoders[col] = le
        elif nuniq <= 10:
            # Low cardinality: one-hot encoding (no drop_first — same as DataVision)
            dummies = pd.get_dummies(X[col], prefix=col, drop_first=False)
            X = pd.concat([X.drop(columns=[col]), dummies], axis=1)
        else:
            # High cardinality: LabelEncoder + frequency encoding
            le = LabelEncoder()
            X[f'{col}_label'] = le.fit_transform(X[col].astype(str))
            freq = X[col].value_counts(normalize=True)
            X[f'{col}_freq'] = X[col].map(freq)
            label_encoders[col] = le
            X = X.drop(columns=[col])
    
    # Force all to float
    for col in X.columns:
        try:
            X[col] = X[col].astype(float)
        except:
            le = LabelEncoder()
            X[col] = le.fit_transform(X[col].astype(str)).astype(float)
    
    # Handle NaN/Inf
    X = X.replace([np.inf, -np.inf], 0)
    X = X.fillna(0)
    
    # VarianceThreshold (remove near-constant features)
    try:
        vt = VarianceThreshold(threshold=0.01)
        cols_before = X.columns.tolist()
        X_filtered = pd.DataFrame(vt.fit_transform(X), columns=X.columns[vt.get_support()], index=X.index)
        removed = len(cols_before) - X_filtered.shape[1]
        if removed > 0:
            print(f"   VarianceThreshold removed {removed} near-constant features")
        X = X_filtered
    except:
        pass
    
    print(f"   Final features: {X.shape[1]}")
    return X, label_encoders, scaler


# ============================================================================
# STEP 3: YOUR EXACT TRAINED MODEL
# ============================================================================

# These are the EXACT hyperparameters from YOUR trained model
ACTUAL_MODEL_CLASS = 'RandomForestClassifier'
ACTUAL_MODEL_PARAMS = {'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 150, 'random_state': 42}

def get_exact_trained_model():
    """Returns YOUR exact model with the SAME hyperparameters as AutoML used.
    
    This ensures retraining produces the SAME results as your AutoML session.
    """
    params = ACTUAL_MODEL_PARAMS.copy()
    
    # Remove non-constructor / problematic params that cause crashes
    for bad_key in ['oob_score', 'warm_start', 'verbose', 'callbacks',
                    'early_stopping_rounds', 'use_label_encoder', 'gpu_id',
                    'predictor', 'enable_categorical', 'feature_types',
                    'validate_parameters', 'nthread', 'device',
                    'n_jobs', 'silent', 'importance_type',
                    'cat_features', 'text_features', 'task_type',
                    'multi_strategy', 'max_cat_to_onehot', 'max_cat_threshold',
                    'num_parallel_tree', 'monotone_constraints',
                    'interaction_constraints', 'grow_policy', 'max_leaves',
                    'process_type', 'updater', 'refresh_leaf', 'max_bin',
                    'bootstrap_type', 'devices', 'embedding_features']:
        params.pop(bad_key, None)
    # Remove private params
    params = {k: v for k, v in params.items() if not k.startswith('_')}
    
    
    return {'RandomForest': RandomForestClassifier(**params)}


def get_single_model(model_name, n_samples):
    """Get ONLY your winning model.
    
    Uses get_exact_trained_model() to get YOUR exact hyperparameters.
    """
    # First try to use exact trained model params
    if model_name == BEST_MODEL_NAME or model_name == 'RandomForest':
        return get_exact_trained_model()
    
    # Otherwise fall back to generic models
    is_large = n_samples > 50000
    all_models = get_models(n_samples, mode='fast')
    
    # Try exact match first
    if model_name in all_models:
        return {model_name: all_models[model_name]}
    
    # Try case-insensitive match
    model_name_lower = model_name.lower().replace('_', '').replace(' ', '')
    for k, v in all_models.items():
        if k.lower().replace('_', '').replace(' ', '') == model_name_lower:
            return {k: v}
    
    # Check in ultra models too
    all_models = get_models(n_samples, mode='ultra')
    if model_name in all_models:
        return {model_name: all_models[model_name]}
    for k, v in all_models.items():
        if k.lower().replace('_', '').replace(' ', '') == model_name_lower:
            return {k: v}
    
    # Fallback to exact trained model
    print(f"   ⚠️ Model '{model_name}' not found, using your trained model")
    return get_exact_trained_model()


def get_models(n_samples, mode='fast'):
    """Returns the EXACT algorithms & hyperparameters used by DataVision AutoML.
    
    Mirrors ProductionModelTrainer.get_models() with the same conditional
    logic for dataset size and mode.
    """
    is_large = n_samples > 50000
    is_ultra = mode == 'ultra'
    
    
    models = {
        'LogisticRegression': LogisticRegression(
            max_iter=2000, C=0.1, random_state=42, n_jobs=1,
            class_weight='balanced'
        ),
        'RandomForest': RandomForestClassifier(
            n_estimators=100 if is_large else (150 if not is_ultra else 250),
            max_depth=8 if is_large else (12 if not is_ultra else 18),
            min_samples_split=4, random_state=42, n_jobs=-1,
            class_weight='balanced'
        ),
        'GradientBoosting': GradientBoostingClassifier(
            n_estimators=80 if is_large else 120,
            max_depth=5 if is_large else 6,
            learning_rate=0.1, random_state=42, subsample=0.8
        ),
        'HistGradientBoosting': HistGradientBoostingClassifier(
            max_iter=100 if is_large else (150 if not is_ultra else 250),
            max_depth=6 if is_large else (8 if not is_ultra else 12),
            learning_rate=0.1, random_state=42, class_weight='balanced'
        ),
        'GaussianNB': GaussianNB(),
        'ExtraTrees': ExtraTreesClassifier(
            n_estimators=80 if is_large else (100 if not is_ultra else 200),
            max_depth=8 if is_large else (10 if not is_ultra else 15),
            random_state=42, n_jobs=-1, class_weight='balanced'
        ),
    }
    
    if not is_large:
        models['KNN'] = KNeighborsClassifier(n_neighbors=7, weights='distance', n_jobs=-1)
    
    if HAS_XGB:
        models['XGBoost'] = xgb.XGBClassifier(
            n_estimators=100 if is_large else (150 if not is_ultra else 300),
            max_depth=6 if is_large else (7 if not is_ultra else 10),
            learning_rate=0.1 if not is_ultra else 0.05,
            subsample=0.8, colsample_bytree=0.8,
            random_state=42, n_jobs=-1, verbosity=0,
            eval_metric='mlogloss',
            tree_method='hist' if is_large else 'auto',
            scale_pos_weight=10
        )
    if HAS_LGB:
        models['LightGBM'] = lgb.LGBMClassifier(
            n_estimators=100 if is_large else (150 if not is_ultra else 300),
            max_depth=6 if is_large else (7 if not is_ultra else 10),
            learning_rate=0.1 if not is_ultra else 0.05,
            num_leaves=31 if not is_ultra else 50,
            subsample=0.8, colsample_bytree=0.8,
            random_state=42, n_jobs=-1, verbose=-1,
            class_weight='balanced'
        )
    if HAS_CB:
        if is_ultra:
            models['CatBoost'] = CatBoostClassifier(
                iterations=150 if is_large else 300, depth=6 if is_large else 10,
                learning_rate=0.05 if is_large else 0.03,
                l2_leaf_reg=3, random_strength=1, bagging_temperature=0.5,
                random_state=42, verbose=False,
                auto_class_weights='Balanced', allow_writing_files=False
            )
        else:
            models['CatBoost'] = CatBoostClassifier(
                iterations=100, depth=6, learning_rate=0.1,
                random_state=42, verbose=False,
                auto_class_weights='Balanced', allow_writing_files=False
            )
    
    # Ultra mode adds more algorithms
    if is_ultra:
        if not is_large:
            models['SVM_RBF'] = SVC(kernel='rbf', C=1.0, gamma='scale', probability=True, random_state=42, class_weight='balanced')
            models['SVM_Linear'] = SVC(kernel='linear', C=0.5, probability=True, random_state=42, class_weight='balanced')
        models['RidgeClassifier'] = RidgeClassifier(alpha=1.0, random_state=42, class_weight='balanced')
        models['MLP'] = MLPClassifier(
            hidden_layer_sizes=(128, 64) if is_large else (256, 128, 64, 32),
            max_iter=500 if is_large else 1500,
            learning_rate='adaptive', early_stopping=True,
            batch_size=256 if is_large else 'auto',
            validation_fraction=0.1, random_state=42
        )
        models['AdaBoost'] = AdaBoostClassifier(n_estimators=100 if is_large else 150, learning_rate=0.5, random_state=42)
        models['Bagging'] = BaggingClassifier(
            n_estimators=50 if is_large else 100,
            max_samples=0.5 if is_large else 0.8,
            max_features=0.8, random_state=42, n_jobs=-1
        )
        models['SGD'] = SGDClassifier(loss='log_loss', max_iter=1500, random_state=42, class_weight='balanced', early_stopping=True)
        models['PassiveAggressive'] = PassiveAggressiveClassifier(max_iter=1500, random_state=42, class_weight='balanced')
        models['DecisionTree'] = DecisionTreeClassifier(max_depth=12 if is_large else 18, min_samples_split=3, random_state=42, class_weight='balanced')
        models['BernoulliNB'] = BernoulliNB(alpha=0.5)

    return models


# ============================================================================
# STEP 4: TRAINING (mirrors ProductionModelTrainer.train_all())
# ============================================================================

def apply_smote(X_train, y_train):
    """Apply SMOTE for imbalanced classification (same as DataVision).
    
    Only applied when:
    - imbalance_ratio > 1.5
    - min class count >= 6
    Falls back to class_weight='balanced' if SMOTE fails.
    """
    if not HAS_SMOTE or TASK_TYPE != 'classification':
        return X_train, y_train, False
    
    class_counts = pd.Series(y_train).value_counts()
    max_count = class_counts.max()
    min_count = class_counts.min()
    imbalance_ratio = max_count / max(min_count, 1)
    
    if imbalance_ratio <= 1.5 or min_count < 6:
        return X_train, y_train, False
    
    try:
        k_neighbors = min(5, min_count - 1)
        n_classes = len(class_counts)
        
        if n_classes == 2:
            if imbalance_ratio > 100:
                sampling_strategy = 0.1
            elif imbalance_ratio > 20:
                sampling_strategy = 0.25
            else:
                sampling_strategy = 1.0
        else:
            sampling_strategy = 'not majority' if imbalance_ratio > 20 else 'auto'
        
        smote = SMOTE(k_neighbors=k_neighbors, sampling_strategy=sampling_strategy, random_state=42)
        X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
        print(f"   ⚖️ SMOTE applied: {len(X_train)} → {len(X_resampled)} samples (ratio: {imbalance_ratio:.1f}x)")
        return X_resampled, y_resampled, True
    except Exception as e:
        print(f"   ⚠️ SMOTE failed ({e}), using class_weight='balanced'")
        return X_train, y_train, False


def train_and_evaluate(X_train, X_test, y_train, y_test, mode='fast', selected_models=None):
    """Train models with real DataVision scoring logic.
    
    Args:
        selected_models: Optional dict of {name: model} to train only specific models.
                        If None, trains all models for the specified mode.
    
    Scoring:
    - Classification (balanced): F1-macro
    - Classification (imbalanced >5x): minority_recall*0.6 + f1_macro*0.4
    - Regression: R² score
    
    Cross-validation:
    - Fast: 3-fold StratifiedKFold/KFold
    - Ultra: 5-fold
    """
    is_clf = TASK_TYPE == 'classification'
    is_ultra = mode == 'ultra'
    
    # Apply SMOTE (classification only)
    X_train_sm, y_train_sm, smote_applied = apply_smote(X_train, y_train)
    
    # Use selected_models if provided, otherwise get all models for the mode
    if selected_models is not None:
        models = selected_models
    else:
        models = get_models(len(X_train), mode)
    results = []
    best_model = None
    best_score = -999
    best_name = ""
    
    # Check imbalance for scoring
    if is_clf:
        class_counts = pd.Series(y_train).value_counts()
        imbalance_ratio = class_counts.max() / max(class_counts.min(), 1)
        is_imbalanced = imbalance_ratio > 5
        minority_class = class_counts.idxmin()
    
    # Cross-validation setup (same as DataVision)
    cv_folds = 3 if mode == 'fast' else 5
    if is_clf:
        cv = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=42)
    else:
        cv = KFold(n_splits=cv_folds, shuffle=True, random_state=42)
    
    print(f"\n🏋️ Training {len(models)} model(s) ({'ALL' if selected_models is None else 'SELECTED'} mode, {cv_folds}-fold CV)...")
    print("=" * 70)
    
    for name, model in models.items():
        try:
            t0 = time.time()
            model.fit(X_train_sm, y_train_sm)
            y_pred = model.predict(X_test)
            elapsed = time.time() - t0
            
            if is_clf:
                f1_macro = f1_score(y_test, y_pred, average='macro', zero_division=0)
                
                if is_imbalanced and len(pd.Series(y_train).unique()) == 2:
                    # DataVision's real scoring for imbalanced binary: 
                    # minority_recall * 0.6 + f1_macro * 0.4
                    from sklearn.metrics import recall_score as rs
                    minority_recall = rs(y_test, y_pred, pos_label=minority_class, zero_division=0)
                    score = minority_recall * 0.6 + f1_macro * 0.4
                else:
                    score = f1_macro
                
                metrics = {
                    'accuracy': accuracy_score(y_test, y_pred),
                    'precision': precision_score(y_test, y_pred, average='weighted', zero_division=0),
                    'recall': recall_score(y_test, y_pred, average='weighted', zero_division=0),
                    'f1_weighted': f1_score(y_test, y_pred, average='weighted', zero_division=0),
                    'f1_macro': f1_macro,
                    'score': score,
                }
            else:
                score = r2_score(y_test, y_pred)
                metrics = {
                    'r2': score,
                    'mae': mean_absolute_error(y_test, y_pred),
                    'rmse': np.sqrt(mean_squared_error(y_test, y_pred)),
                    'score': score,
                }
            
            # Cross-validation
            try:
                cv_scoring = 'f1_weighted' if is_clf else 'r2'
                cv_scores = cross_val_score(model, X_train_sm, y_train_sm, cv=cv, scoring=cv_scoring)
                metrics['cv_mean'] = cv_scores.mean()
                metrics['cv_std'] = cv_scores.std()
            except:
                metrics['cv_mean'] = score
                metrics['cv_std'] = 0
            
            results.append({
                'name': name, 'score': score, 'metrics': metrics, 'model': model,
                'y_pred': y_pred, 'time': elapsed, 'cv_mean': metrics.get('cv_mean', score)
            })
            
            marker = "🏆" if score > best_score else "  "
            cv_str = f"CV: {metrics.get('cv_mean', 0):.4f}±{metrics.get('cv_std', 0):.3f}"
            print(f"   {marker} {name:.<30} Score: {score:.4f} | {cv_str} ({elapsed:.1f}s)")
            
            if score > best_score:
                best_score = score
                best_model = model
                best_name = name
                
        except Exception as e:
            print(f"   ❌ {name:.<30} Failed: {str(e)[:60]}")
    
    # Sort results by score
    results.sort(key=lambda x: x['score'], reverse=True)
    
    print("=" * 70)
    
    if not results:
        print("\n❌ All models failed to train!")
        print("   Try: python train_traditional.py --all  (to try all algorithms)")
        return None, '', {}, []
    
    print(f"\n🏆 Best Model: {best_name} (Score: {best_score:.4f})")
    
    best_result = results[0]
    if is_clf:
        print(f"\n📊 Classification Report:")
        print(classification_report(y_test, best_result['y_pred']))
    else:
        print(f"\n📊 Regression Metrics:")
        for k, v in best_result['metrics'].items():
            if k not in ('score', 'cv_mean', 'cv_std'):
                print(f"   {k.upper()}: {v:.4f}")
    
    # Overfitting check (same as DataVision's Production Intelligence)
    y_pred_train = best_model.predict(X_train)
    if is_clf:
        train_score = accuracy_score(y_train, y_pred_train)
        test_score = accuracy_score(y_test, best_result['y_pred'])
    else:
        train_score = r2_score(y_train, y_pred_train)
        test_score = r2_score(y_test, best_result['y_pred'])
    gap = train_score - test_score
    if gap > 0.1:
        print(f"\n⚠️ Overfitting detected (train-test gap: {gap:.4f})")
    elif gap < 0.02:
        print(f"\n✅ Good generalization (train-test gap: {gap:.4f})")
    
    return best_model, best_name, best_result['metrics'], results


def main():
    parser = argparse.ArgumentParser(description="Train ML model (reproduces your DataVision AutoML)")
    parser.add_argument('--data', type=str, default='data/cleaned_data.csv', help='Path to CSV data file')
    parser.add_argument('--output', type=str, default='model.pkl', help='Output model file')
    parser.add_argument('--test-size', type=float, default=0.2, help='Test split ratio (DataVision uses 0.2)')
    parser.add_argument('--all', action='store_true', help='Train ALL algorithms (like full AutoML)')
    parser.add_argument('--mode', type=str, default='fast', choices=['fast', 'ultra'],
                        help='Training mode when using --all (fast: ~10 models, ultra: ~25 models)')
    args = parser.parse_args()
    
    print("\n" + "=" * 70)
    if args.all:
        print("🚀 DataVision AutoML — Training ALL Algorithms")
    else:
        print(f"🚀 DataVision AutoML — Training YOUR Winning Model: RandomForest")
        print("   (Use --all to train all algorithms like full AutoML)")
    print("=" * 70)
    
    if not os.path.exists(args.data):
        print(f"❌ Data file not found: {args.data}")
        return
    
    start_time = time.time()
    
    # Load data
    df = pd.read_csv(args.data)
    
    # Step 1: Clean data (ProductionDataCleaner)
    df = clean_data(df)
    df = df.dropna(subset=[TARGET_COLUMN])
    
    # Separate target BEFORE feature engineering (anti-leakage — same as DataVision)
    X = df.drop(columns=[TARGET_COLUMN])
    y = df[TARGET_COLUMN]
    
    # Encode target
    target_encoder = None
    if TASK_TYPE == 'classification':
        target_encoder = LabelEncoder()
        y = pd.Series(target_encoder.fit_transform(y), name=TARGET_COLUMN)
        print(f"\n🎯 Target: price_range ({len(target_encoder.classes_)} classes: {list(target_encoder.classes_)[:10]})")
    else:
        print(f"\n🎯 Target: price_range (regression)")
    
    # Train/test split BEFORE feature engineering (anti-leakage)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=args.test_size, random_state=42,
        stratify=y if TASK_TYPE == 'classification' else None
    )
    print(f"📦 Split: {len(X_train)} train / {len(X_test)} test")
    print(f"   ⚠️ Feature engineering applied on train ONLY (anti-leakage)")
    
    # Step 2: Feature engineering (fit on train, transform test — anti-leakage)
    X_train_eng, label_encoders, scaler = engineer_features(X_train.copy(), mode=args.mode)
    
    # Transform test set using same encoding (simplified — uses same column structure)
    X_test_eng = X_test.copy()
    # Apply same encoding to test
    for col in X_test_eng.select_dtypes(include=['object', 'category']).columns:
        if col in label_encoders:
            le = label_encoders[col]
            X_test_eng[col] = X_test_eng[col].astype(str).map(
                lambda x: le.transform([x])[0] if x in le.classes_ else 0
            )
        else:
            le = LabelEncoder()
            X_test_eng[col] = le.fit_transform(X_test_eng[col].astype(str))
    for col in X_test_eng.select_dtypes(include=['object', 'category']).columns:
        X_test_eng[col] = pd.to_numeric(X_test_eng[col], errors='coerce').fillna(0)
    X_test_eng = X_test_eng.fillna(0)
    X_test_eng = X_test_eng.replace([np.inf, -np.inf], 0)
    
    # Ensure same columns as train
    for col in X_train_eng.columns:
        if col not in X_test_eng.columns:
            X_test_eng[col] = 0
    X_test_eng = X_test_eng[X_train_eng.columns]
    for col in X_test_eng.columns:
        X_test_eng[col] = pd.to_numeric(X_test_eng[col], errors='coerce').fillna(0)
    
    # Step 3 & 4: Train models
    # DEFAULT: Train ONLY your winning model (to reproduce exact result)
    # --all: Train all algorithms like full AutoML
    if args.all:
        print(f"\n📊 Training ALL models (mode={args.mode})...")
        best_model, best_name, metrics, all_results = train_and_evaluate(
            X_train_eng, X_test_eng, y_train, y_test, mode=args.mode
        )
    else:
        print(f"\n📊 Training ONLY your winning model: RandomForest")
        models = get_single_model(BEST_MODEL_NAME, len(X_train_eng))
        best_model, best_name, metrics, all_results = train_and_evaluate(
            X_train_eng, X_test_eng, y_train, y_test, mode=args.mode, selected_models=models
        )
    
    if best_model is None:
        print("\n⚠️ Selected model failed. Retrying with ALL algorithms...")
        best_model, best_name, metrics, all_results = train_and_evaluate(
            X_train_eng, X_test_eng, y_train, y_test, mode='fast'
        )
    
    if best_model is None:
        print("\n❌ All models failed. Check your data and dependencies.")
        return
    
    total_time = time.time() - start_time
    
    # Save model state (same structure as DataVision's engine_state)
    engine_state = {
        'model': best_model,
        'model_name': best_name,
        'task_type': TASK_TYPE,
        'task_type_simple': TASK_TYPE,
        'target_column': TARGET_COLUMN,
        'feature_columns': X_train_eng.columns.tolist(),
        'label_encoders': label_encoders,
        'target_encoder': target_encoder,
        'scaler': scaler,
        'metrics': metrics,
        'production_mode': True,
        'mode': args.mode,
        'training_time_seconds': total_time,
        'leaderboard': [
            {'name': r['name'], 'score': r['score'], 'metrics': r['metrics'], 'time': r.get('time', 0)}
            for r in all_results
        ],
    }
    
    with open(args.output, 'wb') as f:
        pickle.dump(engine_state, f)
    
    file_size = os.path.getsize(args.output) / 1024
    print(f"\n💾 Model saved to: {args.output} ({file_size:.1f} KB)")
    print(f"⏱️ Total time: {total_time:.1f}s")
    print("✅ Training complete!")


if __name__ == '__main__':
    main()
