import pandas as pd
import numpy as np

def get_premium_layout(title=""):
    return {
        "title": {
            "text": f"<b>{title}</b>",
            "font": {"size": 13, "color": "#f8fafc", "family": "Inter, system-ui, sans-serif"}
        },
        "paper_bgcolor": "rgba(0,0,0,0)",
        "plot_bgcolor": "rgba(0,0,0,0)",
        "transition": {"duration": 750, "easing": "cubic-in-out"},
        "font": {"color": "#94a3b8", "family": "Inter, system-ui, sans-serif"},
        "margin": {"l": 30, "r": 15, "t": 40, "b": 30},
        "hoverlabel": {
            "bgcolor": "rgba(15, 23, 42, 0.9)",
            "bordercolor": "rgba(255, 255, 255, 0.1)",
            "font": {"size": 12, "color": "#ffffff", "family": "Inter, system-ui, sans-serif"}
        },
        "xaxis": {
            "type": "category",
            "showgrid": True,
            "gridcolor": "rgba(255,255,255,0.04)",
            "zeroline": False,
            "showline": False,
            "tickfont": {"size": 10, "color": "#64748b"}
        },
        "yaxis": {
            "showgrid": True,
            "gridcolor": "rgba(255,255,255,0.04)",
            "zeroline": False,
            "showline": False,
            "tickfont": {"size": 10, "color": "#64748b"}
        },
        "legend": {
            "orientation": "h",
            "yanchor": "bottom",
            "y": -0.3,
            "xanchor": "center",
            "x": 0.5,
            "font": {"size": 10, "color": "#cbd5e1"}
        },
        "hovermode": "closest",
        "showlegend": True
    }

def execute_llm_chart_spec(df: pd.DataFrame, spec: dict, palette: list) -> dict:
    """
    Executes a chart specification generated by the LLM and returns a premium Plotly config.
    """
    try:
        title = spec.get("title", "Generated Chart")
        chart_type = spec.get("chart_type", "bar")
        x_col = spec.get("x_column")
        y_col = spec.get("y_column")
        color_col = spec.get("color_by_column")
        agg = spec.get("aggregation", "sum")
        
        # Validate columns strictly
        if not x_col or x_col not in df.columns:
            print(f"Universal Builder Error: Invalid x_col '{x_col}'")
            return None
        if not y_col or y_col not in df.columns:
            print(f"Universal Builder Error: Invalid y_col '{y_col}'")
            return None
        if color_col and color_col not in df.columns:
            color_col = None
        
        # ---------------------------------------------------------
        # AGGREGATION & GROUPING
        # ---------------------------------------------------------
        data_traces = []
        layout = get_premium_layout(title)
        
        if chart_type in ["stacked_bar", "grouped_bar", "line", "area"]:
            if color_col and color_col != x_col and color_col != y_col:
                # Group by X and Color
                grouped = df.groupby([x_col, color_col])[y_col].agg(agg).reset_index()
                top_x = df[x_col].value_counts().nlargest(12).index
                top_color = df[color_col].value_counts().nlargest(6).index
                
                filtered = grouped[grouped[x_col].isin(top_x) & grouped[color_col].isin(top_color)]
                pivot = filtered.pivot(index=x_col, columns=color_col, values=y_col).fillna(0)
                
                for i, col in enumerate(pivot.columns):
                    trace = {
                        "x": [str(x)[:15] for x in pivot.index],
                        "y": pivot[col].tolist(),
                        "name": str(col)[:15],
                        "marker": {"color": palette[i % len(palette)]},
                        "line": {"color": palette[i % len(palette)], "width": 3, "shape": "spline"}
                    }
                    if chart_type in ["stacked_bar", "grouped_bar"]:
                        trace["type"] = "bar"
                    elif chart_type == "line":
                        trace["type"] = "scatter"
                        trace["mode"] = "lines+markers"
                        trace["marker"] = {"size": 6, "color": palette[i % len(palette)], "line": {"width": 1, "color": "#fff"}}
                    elif chart_type == "area":
                        trace["type"] = "scatter"
                        trace["mode"] = "lines"
                        trace["fill"] = "tozeroy"
                        trace["fillcolor"] = palette[i % len(palette)] + "40"
                    data_traces.append(trace)
                
                if chart_type == "stacked_bar":
                    layout["barmode"] = "stack"
                elif chart_type == "grouped_bar":
                    layout["barmode"] = "group"
                    
            else:
                # Single grouping
                grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(12)
                trace = {
                    "x": [str(x)[:15] for x in grouped.index],
                    "y": [float(y) for y in grouped.values],
                    "name": str(y_col),
                    "marker": {"color": palette[0] if chart_type in ["line", "area"] else palette[:len(grouped)]},
                    "line": {"color": palette[0], "width": 3, "shape": "spline"}
                }
                if chart_type in ["stacked_bar", "grouped_bar"]:
                    trace["type"] = "bar"
                elif chart_type == "line":
                    trace["type"] = "scatter"
                    trace["mode"] = "lines+markers"
                elif chart_type == "area":
                    trace["type"] = "scatter"
                    trace["mode"] = "lines"
                    trace["fill"] = "tozeroy"
                    trace["fillcolor"] = palette[0] + "40"
                data_traces.append(trace)
                
        elif chart_type == "horizontal_bar":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(10).sort_values(ascending=True)
            trace = {
                "type": "bar",
                "orientation": "h",
                "y": [str(y)[:15] for y in grouped.index],
                "x": [float(v) for v in grouped.values],
                "marker": {"color": palette[:len(grouped)]}
            }
            layout["yaxis"]["automargin"] = True
            data_traces.append(trace)
            
        elif chart_type in ["pie", "donut"]:
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(8)
            trace = {
                "type": "pie",
                "labels": [str(l)[:20] for l in grouped.index],
                "values": [float(v) for v in grouped.values],
                "hole": 0.65 if chart_type == "donut" else 0,
                "textinfo": "percent",
                "textfont": {"color": "#fff", "size": 10, "weight": "bold"},
                "marker": {
                    "colors": palette[:len(grouped)],
                    "line": {"color": "#0a0e1a", "width": 2} # Dark background border
                }
            }
            data_traces.append(trace)
            
        elif chart_type == "scatter":
            sample = df.dropna(subset=[x_col, y_col]).head(200)
            if color_col and color_col in df.columns:
                for i, color_val in enumerate(sample[color_col].value_counts().nlargest(5).index):
                    subset = sample[sample[color_col] == color_val]
                    trace = {
                        "type": "scatter",
                        "mode": "markers",
                        "name": str(color_val)[:15],
                        "x": [str(x) for x in subset[x_col].tolist()], # Force category
                        "y": subset[y_col].tolist(),
                        "marker": {
                            "size": 6,
                            "color": palette[i % len(palette)],
                            "opacity": 0.8,
                            "line": {"width": 1, "color": "rgba(255,255,255,0.5)"}
                        }
                    }
                    data_traces.append(trace)
                layout["xaxis"]["type"] = "-"
            else:
                trace = {
                    "type": "scatter",
                    "mode": "markers",
                    "x": [str(x) for x in sample[x_col].tolist()], # Force category
                    "y": sample[y_col].tolist(),
                    "marker": {
                        "size": 6,
                        "color": palette[0],
                        "opacity": 0.8,
                        "line": {"width": 1, "color": "rgba(255,255,255,0.5)"}
                    }
                }
                data_traces.append(trace)
                layout["xaxis"]["type"] = "-"
                
        elif chart_type == "bubble":
            sample = df.dropna(subset=[x_col, y_col]).head(150)
            size_col = color_col if color_col else y_col
            # Normalize sizes to be much smaller
            s_min = sample[size_col].min()
            s_range = sample[size_col].max() - s_min if sample[size_col].max() - s_min > 0 else 1
            sizes = ((sample[size_col] - s_min) / s_range * 12 + 3).tolist()
            
            trace = {
                "type": "scatter",
                "mode": "markers",
                "x": [str(x) for x in sample[x_col].tolist()], # Force categorical for x to prevent massive overlapping
                "y": sample[y_col].tolist(),
                "marker": {
                    "size": sizes,
                    "color": sample[y_col].tolist(),
                    "colorscale": [[0, palette[-1]], [1, palette[0]]],
                    "opacity": 0.8,
                    "line": {"width": 1, "color": "rgba(255,255,255,0.3)"}
                }
            }
            data_traces.append(trace)
            layout["showlegend"] = False
            layout["xaxis"]["type"] = "-" # Allow scatter to use natural axis if needed

        elif chart_type == "treemap":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(15)
            trace = {
                "type": "treemap",
                "labels": [str(l)[:20] for l in grouped.index],
                "parents": [""] * len(grouped),
                "values": [float(v) for v in grouped.values],
                "textinfo": "label+percent entry",
                "marker": {"colors": palette[:len(grouped)]}
            }
            data_traces.append(trace)
            layout["margin"] = {"l": 10, "r": 10, "t": 30, "b": 10}

        elif chart_type == "heatmap":
            if color_col and color_col != x_col and color_col != y_col:
                top_x = df[x_col].value_counts().nlargest(10).index
                top_y = df[color_col].value_counts().nlargest(10).index
                filtered = df[df[x_col].isin(top_x) & df[color_col].isin(top_y)]
                pivot = filtered.groupby([color_col, x_col])[y_col].agg(agg).unstack(fill_value=0)
                
                trace = {
                    "type": "heatmap",
                    "z": pivot.values.tolist(),
                    "x": [str(c)[:15] for c in pivot.columns],
                    "y": [str(i)[:15] for i in pivot.index],
                    "colorscale": [[0, "#0a0e1a"], [0.5, palette[-1]], [1, palette[0]]],
                    "showscale": False
                }
                data_traces.append(trace)

        elif chart_type == "waterfall":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(10)
            trace = {
                "type": "waterfall",
                "x": [str(x)[:15] for x in grouped.index],
                "y": [float(y) for y in grouped.values],
                "measure": ["relative"] * len(grouped),
                "decreasing": {"marker": {"color": "#ef4444"}},
                "increasing": {"marker": {"color": "#22c55e"}},
                "totals": {"marker": {"color": "#3b82f6"}}
            }
            data_traces.append(trace)

        elif chart_type == "funnel":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(8).sort_values(ascending=False)
            trace = {
                "type": "funnel",
                "y": [str(y)[:15] for y in grouped.index],
                "x": [float(x) for x in grouped.values],
                "marker": {"color": palette[:len(grouped)]}
            }
            data_traces.append(trace)

        elif chart_type in ["sunburst", "multi_sunburst"]:
            # Sunburst needs parent/child logic, simpler to just use 2 levels: x_col and color_col
            if color_col and color_col != x_col and color_col in df.columns:
                grouped = df.groupby([x_col, color_col])[y_col].agg(agg).reset_index()
                labels = ["Total"] + grouped[x_col].unique().tolist() + (grouped[x_col] + " - " + grouped[color_col]).tolist()
                parents = [""] + ["Total"] * len(grouped[x_col].unique()) + grouped[x_col].tolist()
                
                # Calculate values
                total_val = grouped[y_col].sum()
                x_vals = grouped.groupby(x_col)[y_col].sum()
                values = [float(total_val)] + [float(x_vals.get(l, 0)) for l in grouped[x_col].unique()] + grouped[y_col].tolist()
                
                trace = {
                    "type": "sunburst",
                    "labels": [str(l)[:25] for l in labels],
                    "parents": [str(p)[:25] for p in parents],
                    "values": [float(v) for v in values],
                    "marker": {"colors": palette}
                }
                data_traces.append(trace)
                layout["margin"] = {"l": 5, "r": 5, "t": 20, "b": 5}
            else:
                grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(10)
                trace = {
                    "type": "sunburst",
                    "labels": [str(l)[:20] for l in grouped.index],
                    "parents": [""] * len(grouped),
                    "values": [float(v) for v in grouped.values],
                    "marker": {"colors": palette[:len(grouped)]}
                }
                data_traces.append(trace)

        elif chart_type == "radar":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(8)
            trace = {
                "type": "scatterpolar",
                "r": [float(v) for v in grouped.values],
                "theta": [str(l)[:15] for l in grouped.index],
                "fill": "toself",
                "fillcolor": palette[0] + "50",
                "line": {"color": palette[0], "width": 2}
            }
            data_traces.append(trace)
            layout["polar"] = {
                "radialaxis": {"visible": True, "gridcolor": "rgba(255,255,255,0.1)", "tickfont": {"size": 8}},
                "angularaxis": {"gridcolor": "rgba(255,255,255,0.1)", "tickfont": {"size": 9}}
            }
            layout["showlegend"] = False
            
        elif chart_type == "polar_bar":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(12)
            trace = {
                "type": "barpolar",
                "r": [float(v) for v in grouped.values],
                "theta": [str(l)[:15] for l in grouped.index],
                "marker": {
                    "color": palette[:len(grouped)] + [palette[0]]*(12-len(grouped)),
                    "line": {"color": "white", "width": 1}
                },
                "opacity": 0.8
            }
            data_traces.append(trace)
            layout["polar"] = {
                "radialaxis": {"visible": True, "gridcolor": "rgba(255,255,255,0.1)"},
                "angularaxis": {"gridcolor": "rgba(255,255,255,0.1)"}
            }
            layout["showlegend"] = False
            
        elif chart_type == "sankey":
            if color_col and color_col in df.columns:
                grouped = df.groupby([x_col, y_col])[color_col].count().reset_index().nlargest(15, color_col)
                nodes = list(set(grouped[x_col].tolist() + grouped[y_col].tolist()))
                node_dict = {node: i for i, node in enumerate(nodes)}
                
                trace = {
                    "type": "sankey",
                    "node": {
                        "pad": 15,
                        "thickness": 20,
                        "line": {"color": "black", "width": 0.5},
                        "label": [str(n)[:15] for n in nodes],
                        "color": palette[:len(nodes)]
                    },
                    "link": {
                        "source": [node_dict[src] for src in grouped[x_col]],
                        "target": [node_dict[tgt] for tgt in grouped[y_col]],
                        "value": [float(v) for v in grouped[color_col]]
                    }
                }
                data_traces.append(trace)
                
        elif chart_type in ["3d_scatter", "3d_surface", "3d_bubble"]:
            if color_col and color_col in df.columns:
                sample = df.dropna(subset=[x_col, y_col, color_col]).head(150)
                
                if chart_type == "3d_surface":
                    trace = {
                        "type": "mesh3d",
                        "x": sample[x_col].tolist(),
                        "y": sample[y_col].tolist(),
                        "z": sample[color_col].tolist(),
                        "opacity": 0.8,
                        "color": palette[0]
                    }
                else:
                    sizes = 5
                    if chart_type == "3d_bubble":
                        s_min = sample[color_col].min() if pd.api.types.is_numeric_dtype(sample[color_col]) else 1
                        s_range = sample[color_col].max() - s_min if pd.api.types.is_numeric_dtype(sample[color_col]) and sample[color_col].max() > s_min else 1
                        sizes = ((sample[color_col] if pd.api.types.is_numeric_dtype(sample[color_col]) else 1) - s_min) / s_range * 15 + 5

                    trace = {
                        "type": "scatter3d",
                        "mode": "markers",
                        "x": sample[x_col].tolist(),
                        "y": sample[y_col].tolist(),
                        "z": sample[color_col].tolist(),
                        "marker": {
                            "size": sizes,
                            "color": sample[color_col].tolist() if pd.api.types.is_numeric_dtype(sample[color_col]) else palette[0],
                            "colorscale": [[0, palette[-1]], [1, palette[0]]],
                            "opacity": 0.8
                        }
                    }
                data_traces.append(trace)
                layout["scene"] = {
                    "xaxis": {"title": str(x_col)[:10], "gridcolor": "rgba(255,255,255,0.1)"},
                    "yaxis": {"title": str(y_col)[:10], "gridcolor": "rgba(255,255,255,0.1)"},
                    "zaxis": {"title": str(color_col)[:10], "gridcolor": "rgba(255,255,255,0.1)"}
                }
                layout["margin"] = {"l": 0, "r": 0, "t": 20, "b": 0}

        elif chart_type == "choropleth":
            grouped = df.groupby(x_col)[y_col].agg(agg).reset_index()
            trace = {
                "type": "choropleth",
                "locationmode": "country names",
                "locations": grouped[x_col].tolist(),
                "z": grouped[y_col].tolist(),
                "colorscale": [[0, palette[-1]], [1, palette[0]]],
                "marker": {"line": {"width": 0.5, "color": "rgb(255,255,255)"}}
            }
            data_traces.append(trace)
            layout["geo"] = {
                "showframe": False,
                "showcoastlines": True,
                "projection": {"type": "orthographic"},
                "bgcolor": "rgba(0,0,0,0)"
            }
            layout["margin"] = {"l": 0, "r": 0, "t": 20, "b": 0}
            
        elif chart_type == "violin":
            sample = df.dropna(subset=[x_col, y_col]).head(500)
            unique_x = sample[x_col].unique()
            for i, x_val in enumerate(unique_x[:5]): # limit to 5 violins max
                subset = sample[sample[x_col] == x_val]
                trace = {
                    "type": "violin",
                    "x": [str(x_val)] * len(subset),
                    "y": subset[y_col].tolist(),
                    "name": str(x_val)[:15],
                    "box": {"visible": True},
                    "meanline": {"visible": True},
                    "line": {"color": palette[i % len(palette)]}
                }
                data_traces.append(trace)

        elif chart_type == "density_contour":
            sample = df.dropna(subset=[x_col, y_col]).head(1000)
            trace = {
                "type": "histogram2dcontour",
                "x": sample[x_col].tolist(),
                "y": sample[y_col].tolist(),
                "colorscale": [[0, "rgba(0,0,0,0)"], [1, palette[0]]]
            }
            data_traces.append(trace)
            
        elif chart_type == "hexbin":
            sample = df.dropna(subset=[x_col, y_col]).head(1000)
            trace = {
                "type": "histogram2d",
                "x": sample[x_col].tolist(),
                "y": sample[y_col].tolist(),
                "colorscale": [[0, "rgba(0,0,0,0)"], [1, palette[0]]],
                "xgap": 1,
                "ygap": 1
            }
            data_traces.append(trace)
            
        elif chart_type == "parallel_categories":
            sample = df.dropna(subset=[x_col, y_col]).head(500)
            trace = {
                "type": "parcats",
                "dimensions": [
                    {"label": str(x_col), "values": sample[x_col].tolist()},
                    {"label": str(y_col), "values": sample[y_col].tolist()}
                ]
            }
            if color_col and color_col in df.columns and pd.api.types.is_numeric_dtype(df[color_col]):
                trace["line"] = {
                    "color": sample[color_col].tolist(),
                    "colorscale": [[0, palette[-1]], [1, palette[0]]]
                }
            data_traces.append(trace)
            
        elif chart_type == "bullet":
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(3)
            for i, (idx, val) in enumerate(grouped.items()):
                # Distribute the 3 bullets vertically
                y0 = i / max(1, len(grouped))
                y1 = (i + 0.7) / max(1, len(grouped))
                trace = {
                    "type": "indicator",
                    "mode": "number+gauge",
                    "value": float(val),
                    "title": {"text": str(idx)[:15]},
                    "gauge": {
                        "shape": "bullet",
                        "axis": {"range": [0, float(val) * 1.5]},
                        "bar": {"color": palette[i % len(palette)]}
                    },
                    "domain": {"x": [0.2, 1], "y": [y0, y1]}
                }
                data_traces.append(trace)
            layout["margin"] = {"l": 10, "r": 20, "t": 20, "b": 20}

        # Fallback to simple bar if type not matched
        if not data_traces:
            grouped = df.groupby(x_col)[y_col].agg(agg).nlargest(10)
            trace = {
                "type": "bar",
                "x": [str(x)[:15] for x in grouped.index],
                "y": [float(y) for y in grouped.values],
                "marker": {"color": palette[:len(grouped)]}
            }
            data_traces.append(trace)

        return {
            "chart_id": f"ai_{chart_type}_{x_col}_{y_col}",
            "title": title,
            "type": chart_type,
            "plotly_config": {
                "data": data_traces,
                "layout": layout
            }
        }
    except Exception as e:
        print(f"Universal Builder Error: {e}")
        return None
