"""
📊 Model Evaluation Script — Shows YOUR AutoML Results
========================================================
Auto-generated by DataVision AI

╔════════════════════════════════════════════════════════════════════╗
║  This script shows the EXACT SAME metrics as your AutoML training. ║
║  Supports Traditional ML, Deep Learning, and NLP models.           ║
╚════════════════════════════════════════════════════════════════════╝

Model         : RandomForest
Target Column : price_range
Task Type     : classification

YOUR AUTOML METRICS:
#   accuracy: 0.8925
#   f1: 0.8929
#   precision: 0.8937
#   recall: 0.8925
#   roc_auc: 0.9796

Usage:
    python evaluate.py                    # Show YOUR AutoML results
    python evaluate.py --reeval           # Re-evaluate with data (may differ)
"""

import os
import pickle
import argparse
import warnings
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    r2_score, mean_absolute_error, mean_squared_error,
    confusion_matrix, classification_report
)
try:
    from sklearn.metrics import roc_auc_score
except ImportError:
    roc_auc_score = None

warnings.filterwarnings('ignore')

TARGET_COLUMN = 'price_range'
TASK_TYPE = 'classification'
BEST_MODE = 'traditional'  # Which mode won during AutoML


def print_classification_metrics(y_test, y_pred, model=None, X_test=None, target_encoder=None):
    """Print all classification metrics including ROC-AUC."""
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    f1_macro = f1_score(y_test, y_pred, average='macro', zero_division=0)
    
    print(f"\n✅ ACCURACY:    {acc:.4f} ({acc*100:.1f}%)")
    print(f"   Precision:   {prec:.4f} ({prec*100:.1f}%)")
    print(f"   Recall:      {rec:.4f} ({rec*100:.1f}%)")
    print(f"   F1-Weighted: {f1:.4f} ({f1*100:.1f}%)")
    print(f"   F1-Macro:    {f1_macro:.4f} ({f1_macro*100:.1f}%)")
    
    # ROC-AUC
    if roc_auc_score is not None and model is not None and X_test is not None:
        try:
            n_classes = len(np.unique(y_test))
            if n_classes == 2 and hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_test)[:, 1]
                roc = roc_auc_score(y_test, y_proba)
                print(f"   ROC-AUC:     {roc:.4f} ({roc*100:.1f}%)")
            elif n_classes > 2 and hasattr(model, 'predict_proba'):
                y_proba = model.predict_proba(X_test)
                roc = roc_auc_score(y_test, y_proba, multi_class='ovr', average='weighted')
                print(f"   ROC-AUC:     {roc:.4f} ({roc*100:.1f}%)")
            elif n_classes == 2 and hasattr(model, 'decision_function'):
                y_scores = model.decision_function(X_test)
                roc = roc_auc_score(y_test, y_scores)
                print(f"   ROC-AUC:     {roc:.4f} ({roc*100:.1f}%)")
        except Exception:
            pass
    
    print("\n📊 Classification Report:")
    if target_encoder is not None:
        try:
            print(classification_report(y_test, y_pred, target_names=target_encoder.classes_))
        except Exception:
            print(classification_report(y_test, y_pred))
    else:
        print(classification_report(y_test, y_pred))
    
    print("\n📊 Confusion Matrix:")
    cm = confusion_matrix(y_test, y_pred)
    print(cm)


def print_regression_metrics(y_test, y_pred):
    """Print all regression metrics."""
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    
    print(f"\n✅ R² SCORE: {r2:.4f}")
    print(f"   MSE:  {mse:.4f}")
    print(f"   RMSE: {rmse:.4f}")
    print(f"   MAE:  {mae:.4f}")


def load_dl_model(dl_path='deep_learning_model.pkl'):
    """Load the Deep Learning model."""
    if not os.path.exists(dl_path):
        return None
    try:
        with open(dl_path, 'rb') as f:
            state = pickle.load(f)
        return state
    except Exception as e:
        print(f"⚠️ Failed to load DL model: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(description="Show your AutoML training results")
    parser.add_argument('--model', type=str, default='model.pkl')
    parser.add_argument('--dl-model', type=str, default='deep_learning_model.pkl', help='Path to DL model file')
    parser.add_argument('--mode', type=str, default='auto', choices=['auto', 'traditional', 'dl'], help='Evaluation mode')
    parser.add_argument('--data', type=str, default='data/cleaned_data.csv')
    parser.add_argument('--reeval', action='store_true', help='Re-evaluate with fresh train/test split (may differ from AutoML)')
    parser.add_argument('--cv', type=int, default=5, help='Number of cross-validation folds for --reeval')
    args = parser.parse_args()
    
    print("\n" + "=" * 60)
    print("📊 DataVision AutoML — Your Training Results")
    print("=" * 60)
    
    # Decide which model to load based on BEST_MODE
    use_dl = False
    state = None
    
    if args.mode == 'dl' or (args.mode == 'auto' and BEST_MODE == 'deep_learning'):
        state = load_dl_model(args.dl_model)
        if state:
            use_dl = True
        else:
            print("⚠️ DL model not found, falling back to traditional ML model...")
    
    if not use_dl and args.mode != 'dl':
        if os.path.exists(args.model):
            with open(args.model, 'rb') as f:
                state = pickle.load(f)
        elif os.path.exists(args.dl_model):
            state = load_dl_model(args.dl_model)
            if state:
                use_dl = True
    
    if state is None:
        print("❌ No model found. Provide model.pkl or deep_learning_model.pkl")
        return
    
    model = state['model']
    task_type = state.get('task_type', TASK_TYPE)
    is_clf = 'classif' in task_type.lower()
    mode_display = 'deep_learning' if use_dl else state.get('mode', 'traditional')
    model_name = state.get('model_name', state.get('algorithm', 'Unknown'))
    
    print(f"\n🏆 Model: {model_name}")
    print(f"🎯 Task: {task_type}")
    print(f"📊 Mode: {mode_display}")
    if use_dl:
        print(f"🧠 Architecture: {state.get('algorithm', 'MLP')}")
        print(f"   Features: {len(state.get('feature_columns', state.get('feature_metadata', [])))}")
    
    # =========================================================================
    # OPTION 1: Use SAVED y_test/y_pred (EXACT same as AutoML showed)
    # =========================================================================
    y_test_saved = state.get('y_test')
    y_pred_saved = state.get('y_pred')
    
    if not args.reeval and y_test_saved is not None and y_pred_saved is not None:
        print("\n" + "=" * 60)
        print("📋 YOUR AUTOML TRAINING RESULTS (from saved predictions)")
        print("=" * 60)
        
        y_test = np.array(y_test_saved)
        y_pred = np.array(y_pred_saved)
        
        # For ROC-AUC we need X_test and the model — try to reconstruct
        X_test_for_roc = None
        if use_dl:
            X_test_saved = state.get('X_test')
            if X_test_saved is not None:
                X_test_for_roc = np.array(X_test_saved)
        
        if is_clf:
            print_classification_metrics(
                y_test, y_pred, model=model,
                X_test=X_test_for_roc,
                target_encoder=state.get('target_encoder') if not use_dl else state.get('label_encoder')
            )
        else:
            print_regression_metrics(y_test, y_pred)
        
        # Also show stored metrics
        stored_metrics = state.get('metrics', {})
        if stored_metrics:
            print("\n📋 Stored Metrics from Training:")
            for k, v in stored_metrics.items():
                if isinstance(v, float):
                    print(f"   {k}: {v:.4f}")
                else:
                    print(f"   {k}: {v}")
        
        print("\n" + "=" * 60)
        print("✅ These are your EXACT AutoML results.")
        print("   Use --reeval to re-evaluate with fresh data split (may differ).")
        print("=" * 60)
        return
    
    # =========================================================================
    # OPTION 2: Re-evaluate (may produce different results due to random split)
    # =========================================================================
    print("\n⚠️ Re-evaluating with fresh train/test split...")
    print("   Note: Results may differ from AutoML due to different random split.")
    
    if not os.path.exists(args.data):
        print(f"⚠️ Data file not found: {args.data}")
        print("   Showing stored metrics only:")
        for k, v in state.get('metrics', {}).items():
            print(f"   {k}: {v}")
        return
    
    df = pd.read_csv(args.data)
    target_col = state.get('target_column', TARGET_COLUMN)
    feature_cols = state.get('feature_columns', [])
    
    if target_col not in df.columns:
        print(f"❌ Target '{target_col}' not in data")
        return
    
    df = df.dropna(subset=[target_col])
    
    if use_dl:
        # =====================================================================
        # DL Re-evaluation: Use the DL model's preprocessing pipeline
        # =====================================================================
        feature_metadata = state.get('feature_metadata', [])
        scaler = state.get('scaler')
        label_encoder = state.get('label_encoder')
        
        # Build feature matrix from metadata
        X_parts = []
        for meta in feature_metadata:
            col = meta['name']
            if meta.get('type') == 'numeric':
                if col in df.columns:
                    X_parts.append(df[col].apply(pd.to_numeric, errors='coerce').fillna(meta.get('mean', 0)).values.reshape(-1, 1))
                else:
                    X_parts.append(np.full((len(df), 1), meta.get('mean', 0)))
            elif meta.get('type') == 'categorical':
                if col in df.columns:
                    encoding = meta.get('encoding', {})
                    X_parts.append(df[col].astype(str).map(lambda v: encoding.get(v, 0)).values.reshape(-1, 1))
                else:
                    X_parts.append(np.zeros((len(df), 1)))
        
        if X_parts:
            X = np.hstack(X_parts).astype(float)
        else:
            X = df.drop(columns=[target_col]).select_dtypes(include=[np.number]).fillna(0).values
        
        y = df[target_col].values
        if is_clf and label_encoder:
            try:
                y = label_encoder.transform(y)
            except Exception:
                le = LabelEncoder()
                y = le.fit_transform(y)
        
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        # Scale AFTER split (same as training)
        if scaler:
            X_train = scaler.transform(X_train)
            X_test = scaler.transform(X_test)
        
        y_pred = model.predict(X_test)
        
        if is_clf:
            print(f"\n📊 Deep Learning Classification Metrics (re-evaluated):")
            print_classification_metrics(y_test, y_pred, model=model, X_test=X_test,
                                       target_encoder=label_encoder)
        else:
            print(f"\n📊 Deep Learning Regression Metrics (re-evaluated):")
            print_regression_metrics(y_test, y_pred)
    else:
        # =====================================================================
        # Traditional ML Re-evaluation
        # =====================================================================
        X = df.drop(columns=[target_col])
        y = df[target_col]
        
        target_encoder = state.get('target_encoder')
        if is_clf and target_encoder:
            y = pd.Series(target_encoder.transform(y))
        
        label_encoders = state.get('label_encoders', {})
        for col in X.select_dtypes(include=['object', 'category']).columns:
            if col in label_encoders:
                try:
                    X[col] = label_encoders[col].transform(X[col].astype(str))
                except:
                    le = LabelEncoder()
                    X[col] = le.fit_transform(X[col].astype(str))
            else:
                le = LabelEncoder()
                X[col] = le.fit_transform(X[col].astype(str))
        
        X = X.fillna(0)
        
        scaler = state.get('scaler')
        if scaler and feature_cols:
            avail = [c for c in feature_cols if c in X.columns]
            if avail:
                X = X[avail]
                X = pd.DataFrame(scaler.transform(X), columns=avail)
        
        # Align columns with model's expected features
        if feature_cols:
            for col in feature_cols:
                if col not in X.columns:
                    X[col] = 0
            X = X.reindex(columns=feature_cols, fill_value=0)
        
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        
        y_pred = model.predict(X_test)
        y_pred_train = model.predict(X_train)
        
        if is_clf:
            print(f"\n📊 Classification Metrics (re-evaluated):")
            print_classification_metrics(y_test, y_pred, model=model, X_test=X_test,
                                       target_encoder=state.get('target_encoder'))
            
            # Overfitting check
            train_acc = accuracy_score(y_train, y_pred_train)
            test_acc = accuracy_score(y_test, y_pred)
            gap = train_acc - test_acc
            if gap > 0.1:
                print(f"\n⚠️ Overfitting detected (train-test gap: {gap:.4f})")
            elif gap < 0.01:
                print(f"\n✅ Good generalization (train-test gap: {gap:.4f})")
            
            try:
                cv_scores = cross_val_score(model, X, y, cv=args.cv, scoring='accuracy')
                print(f"\n🔄 {args.cv}-Fold CV Accuracy: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
            except Exception as e:
                print(f"   CV failed: {e}")
        else:
            print(f"\n📊 Regression Metrics (re-evaluated):")
            print_regression_metrics(y_test, y_pred)
            
            try:
                cv_scores = cross_val_score(model, X, y, cv=args.cv, scoring='r2')
                print(f"\n🔄 {args.cv}-Fold CV R²: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
            except:
                pass
    
    print("\n✅ Evaluation complete!")


if __name__ == '__main__':
    main()
