"""
📊 Visualization Script — ALL Charts Matching DataVision AutoML
================================================================
Auto-generated by DataVision AI

Model         : RandomForest
Target Column : price_range
Task Type     : classification
Features      : 20 columns

Supports Traditional ML AND Deep Learning models.
Automatically loads the correct model based on BEST_MODE.

Generates the SAME charts you see in DataVision AutoML:
  Classification: confusion matrix, class distribution, ROC curve,
                  precision-recall, calibration, confidence histogram,
                  metrics heatmap, feature importance, model comparison,
                  correlation heatmap, feature distributions, boxplots
  Regression:     actual vs predicted, residuals analysis, error distribution,
                  prediction overview, feature importance, model comparison,
                  correlation heatmap, feature distributions, boxplots
  Deep Learning:  training loss curve, validation score curve,
                  model architecture summary, MLP weight importance
  Unsupervised:   KMeans clustering scatter plot (PCA 2D),
                  cluster distribution chart

Usage:
    python visualize.py                         # Auto-detect best model
    python visualize.py --mode dl               # Force Deep Learning model
    python visualize.py --mode traditional      # Force traditional ML model
    python visualize.py --data my_data.csv
    python visualize.py --output charts/
"""

import os
import pickle
import argparse
import warnings
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, label_binarize
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report,
    r2_score, mean_absolute_error, mean_squared_error,
    roc_curve, auc, precision_recall_curve, average_precision_score,
    precision_score, recall_score, f1_score
)

try:
    from sklearn.calibration import calibration_curve
    HAS_CALIBRATION = True
except ImportError:
    HAS_CALIBRATION = False

warnings.filterwarnings('ignore')
sns.set_style("whitegrid")
plt.rcParams.update({
    'figure.figsize': (10, 6),
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
})

TARGET_COLUMN = 'price_range'
TASK_TYPE = 'classification'
BEST_MODE = 'traditional'  # Which mode won during AutoML
NUMERIC_FEATURES = ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt']
LEADERBOARD_NAMES = ['?']
LEADERBOARD_SCORES = [0.8925]


def load_model_and_data(model_path='model.pkl', data_path='data/cleaned_data.csv'):
    if not os.path.exists(model_path):
        print(f"❌ Model not found: {model_path}")
        return None, None
    with open(model_path, 'rb') as f:
        state = pickle.load(f)
    df = pd.read_csv(data_path) if os.path.exists(data_path) else None
    return state, df


def load_dl_model(dl_path='deep_learning_model.pkl'):
    """Load the Deep Learning model (sklearn MLP)."""
    if not os.path.exists(dl_path):
        return None
    try:
        with open(dl_path, 'rb') as f:
            state = pickle.load(f)
        print(f"✅ Loaded DL model: {state.get('algorithm', 'MLP')}")
        print(f"   Task: {state.get('task_type', 'Unknown')}")
        print(f"   Features: {len(state.get('feature_columns', state.get('feature_metadata', [])))}")
        return state
    except Exception as e:
        print(f"⚠️ Failed to load DL model: {e}")
        return None


def generate_charts(state, df, output_dir='charts'):
    os.makedirs(output_dir, exist_ok=True)
    
    model = state['model']
    task_type = state.get('task_type', 'classification')
    target_col = state.get('target_column', TARGET_COLUMN)
    feature_cols = state.get('feature_columns', [])
    is_clf = 'classif' in task_type.lower()
    is_dl = state.get('model_type') == 'deep_learning'
    charts = []
    
    # Load SAVED predictions from AutoML (exact results, no feature mismatch)
    y_test = np.array(state['y_test']) if state.get('y_test') is not None else None
    y_pred = np.array(state['y_pred']) if state.get('y_pred') is not None else None
    y_proba = np.array(state['y_proba']) if state.get('y_proba') is not None else None
    # Handle both ML (target_encoder) and DL (label_encoder) naming
    target_encoder = state.get('target_encoder', None)
    label_encoder = state.get('label_encoder', None)
    encoder = target_encoder or label_encoder
    class_names = list(encoder.classes_) if encoder is not None else None
    mode_display = 'Deep Learning (MLP)' if is_dl else 'Traditional ML'
    model_name = state.get('model_name', state.get('algorithm', 'Unknown'))
    
    print(f"\n📊 Generating charts for {model_name} ({mode_display})...")
    print(f"   Saved predictions: y_test={y_test is not None}, y_pred={y_pred is not None}, y_proba={y_proba is not None}")
    
    # =====================================================================
    # 1. MODEL COMPARISON / LEADERBOARD (same as AutoML)
    # =====================================================================
    if LEADERBOARD_NAMES and LEADERBOARD_SCORES:
        try:
            fig, ax = plt.subplots(figsize=(10, max(4, len(LEADERBOARD_NAMES) * 0.5)))
            colors = sns.color_palette('viridis', len(LEADERBOARD_NAMES))
            y_pos = range(len(LEADERBOARD_NAMES))
            ax.barh(y_pos, LEADERBOARD_SCORES, color=colors)
            ax.set_yticks(y_pos)
            ax.set_yticklabels(LEADERBOARD_NAMES)
            metric_label = 'F1-Score' if is_clf else 'R²'
            ax.set_xlabel(metric_label)
            ax.set_title(f'Model Leaderboard — {metric_label}')
            for i, v in enumerate(LEADERBOARD_SCORES):
                ax.text(v + 0.001, i, f'{v:.4f}', va='center', fontsize=9)
            plt.tight_layout()
            path = os.path.join(output_dir, 'model_comparison.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Model Comparison → {path}")
        except Exception as e:
            print(f"   ⚠️ Model Comparison failed: {e}")
    
    # =====================================================================
    # 2. FEATURE IMPORTANCE (from model)
    # =====================================================================
    try:
        importances = None
        if hasattr(model, 'feature_importances_'):
            # Tree-based models (RF, XGB, etc.)
            importances = model.feature_importances_
        elif hasattr(model, 'coefs_') and len(model.coefs_) > 0:
            # MLP/Neural Network — use mean absolute weight of first layer
            importances = np.mean(np.abs(model.coefs_[0]), axis=1)
        elif hasattr(model, 'coef_'):
            # Linear models (LogReg, SVM, etc.)
            coef = model.coef_
            importances = np.mean(np.abs(coef), axis=0) if coef.ndim > 1 else np.abs(coef)
        
        if importances is not None:
            names = feature_cols[:len(importances)] if feature_cols else [f'Feature_{i}' for i in range(len(importances))]
            fi = pd.Series(importances, index=names).nlargest(min(20, len(names)))
            
            fig, ax = plt.subplots(figsize=(10, max(4, len(fi) * 0.35)))
            bars = fi.sort_values().plot(kind='barh', ax=ax, 
                color=plt.cm.viridis(np.linspace(0.2, 0.8, len(fi))))
            title_suffix = ' (MLP Weight Magnitude)' if is_dl else ''
            ax.set_title(f'Feature Importance — Top Features{title_suffix}')
            ax.set_xlabel('Importance')
            for i, (val, name) in enumerate(zip(fi.sort_values(), fi.sort_values().index)):
                ax.text(val + 0.001, i, f'{val:.4f}', va='center', fontsize=8)
            plt.tight_layout()
            path = os.path.join(output_dir, 'feature_importance.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Feature Importance → {path}")
    except Exception as e:
        print(f"   ⚠️ Feature Importance failed: {e}")
    
    # =====================================================================
    # DL-SPECIFIC: TRAINING HISTORY (loss curve + validation score)
    # =====================================================================
    if is_dl:
        training_history = state.get('training_history', {})
        loss_curve = training_history.get('loss', [])
        val_scores = training_history.get('val_score', [])
        
        if loss_curve:
            try:
                n_plots = 1 + (1 if val_scores else 0)
                fig, axes = plt.subplots(1, n_plots, figsize=(6 * n_plots, 5))
                if n_plots == 1:
                    axes = [axes]
                
                # Loss curve
                axes[0].plot(range(1, len(loss_curve) + 1), loss_curve, color='#EF4444', lw=2)
                axes[0].set_xlabel('Epoch')
                axes[0].set_ylabel('Loss')
                axes[0].set_title('Training Loss Curve')
                axes[0].grid(True, alpha=0.3)
                
                # Validation score curve
                if val_scores and n_plots > 1:
                    axes[1].plot(range(1, len(val_scores) + 1), val_scores, color='#22C55E', lw=2)
                    axes[1].set_xlabel('Epoch')
                    axes[1].set_ylabel('Validation Score')
                    axes[1].set_title('Validation Score Curve')
                    axes[1].grid(True, alpha=0.3)
                
                plt.suptitle(f'Deep Learning Training History — {state.get("algorithm", "MLP")}', fontsize=14)
                plt.tight_layout()
                path = os.path.join(output_dir, 'training_history.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Training History → {path}")
            except Exception as e:
                print(f"   ⚠️ Training History failed: {e}")
        
        # DL Model Architecture Summary
        try:
            fig, ax = plt.subplots(figsize=(8, 4))
            ax.axis('off')
            info_lines = [
                f"Model: {state.get('algorithm', 'MLP')}",
                f"Task: {state.get('task_type', 'Unknown')}",
                f"Features: {len(feature_cols)}",
            ]
            if hasattr(model, 'hidden_layer_sizes'):
                info_lines.append(f"Hidden Layers: {model.hidden_layer_sizes}")
            if hasattr(model, 'activation'):
                info_lines.append(f"Activation: {model.activation}")
            if hasattr(model, 'n_iter_'):
                info_lines.append(f"Epochs Trained: {model.n_iter_}")
            metrics = state.get('metrics', {})
            if metrics:
                info_lines.append("")
                info_lines.append("Metrics:")
                for k, v in metrics.items():
                    if isinstance(v, float):
                        info_lines.append(f"  {k}: {v:.4f}")
            text = "\n".join(info_lines)
            ax.text(0.1, 0.9, text, transform=ax.transAxes, fontsize=12,
                   verticalalignment='top', fontfamily='monospace',
                   bbox=dict(boxstyle='round', facecolor='#F0F9FF', alpha=0.8))
            ax.set_title('Deep Learning Model Summary', fontsize=14, fontweight='bold')
            plt.tight_layout()
            path = os.path.join(output_dir, 'dl_model_summary.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ DL Model Summary → {path}")
        except Exception as e:
            print(f"   ⚠️ DL Model Summary failed: {e}")
    
    # =====================================================================
    # CLASSIFICATION-SPECIFIC CHARTS
    # =====================================================================
    if is_clf and y_test is not None and y_pred is not None:
        n_classes = len(np.unique(y_test))
        is_binary = n_classes == 2
        
        # --- 3. CONFUSION MATRIX (normalized + counts) ---
        try:
            cm = confusion_matrix(y_test, y_pred)
            cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)
            labels = class_names if class_names else sorted(np.unique(y_test).tolist())
            
            fig, axes = plt.subplots(1, 2, figsize=(14, 5))
            # Counts
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
                       xticklabels=labels, yticklabels=labels)
            axes[0].set_title('Confusion Matrix (Counts)')
            axes[0].set_xlabel('Predicted')
            axes[0].set_ylabel('Actual')
            # Normalized
            sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues', ax=axes[1],
                       xticklabels=labels, yticklabels=labels)
            axes[1].set_title('Confusion Matrix (Normalized)')
            axes[1].set_xlabel('Predicted')
            axes[1].set_ylabel('Actual')
            plt.tight_layout()
            path = os.path.join(output_dir, 'confusion_matrix.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Confusion Matrix → {path}")
        except Exception as e:
            print(f"   ⚠️ Confusion Matrix failed: {e}")
        
        # --- 4. CLASS DISTRIBUTION (actual vs predicted) ---
        try:
            fig, axes = plt.subplots(1, 2, figsize=(12, 5))
            labels = class_names if class_names else sorted(np.unique(y_test).tolist())
            # Actual
            actual_counts = pd.Series(y_test).value_counts().sort_index()
            pred_counts = pd.Series(y_pred).value_counts().sort_index()
            axes[0].bar(range(len(actual_counts)), actual_counts.values, color=sns.color_palette('Set2'))
            axes[0].set_xticks(range(len(actual_counts)))
            axes[0].set_xticklabels(labels, rotation=45, ha='right')
            axes[0].set_title('Actual Distribution')
            axes[0].set_ylabel('Count')
            axes[1].bar(range(len(pred_counts)), pred_counts.reindex(actual_counts.index, fill_value=0).values, 
                       color=sns.color_palette('Set3'))
            axes[1].set_xticks(range(len(actual_counts)))
            axes[1].set_xticklabels(labels, rotation=45, ha='right')
            axes[1].set_title('Predicted Distribution')
            axes[1].set_ylabel('Count')
            plt.suptitle('Class Distribution: Actual vs Predicted', fontsize=14)
            plt.tight_layout()
            path = os.path.join(output_dir, 'class_distribution.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Class Distribution → {path}")
        except Exception as e:
            print(f"   ⚠️ Class Distribution failed: {e}")
        
        # --- 5. ROC CURVE (binary + multi-class) ---
        if y_proba is not None:
            try:
                fig, ax = plt.subplots(figsize=(8, 8))
                if is_binary:
                    proba_pos = y_proba[:, 1] if y_proba.ndim == 2 else y_proba
                    fpr, tpr, _ = roc_curve(y_test, proba_pos)
                    roc_auc = auc(fpr, tpr)
                    ax.plot(fpr, tpr, color='#4F46E5', lw=2, label=f'ROC (AUC = {roc_auc:.4f})')
                else:
                    y_test_bin = label_binarize(y_test, classes=sorted(np.unique(y_test)))
                    colors = plt.cm.Set1(np.linspace(0, 1, n_classes))
                    for i in range(min(n_classes, y_proba.shape[1])):
                        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_proba[:, i])
                        roc_auc = auc(fpr, tpr)
                        label = class_names[i] if class_names and i < len(class_names) else f'Class {i}'
                        ax.plot(fpr, tpr, color=colors[i], lw=2, label=f'{label} (AUC={roc_auc:.3f})')
                ax.plot([0, 1], [0, 1], 'k--', lw=1, alpha=0.5)
                ax.set_xlabel('False Positive Rate')
                ax.set_ylabel('True Positive Rate')
                ax.set_title('ROC Curve')
                ax.legend(loc='lower right')
                ax.set_xlim([0, 1])
                ax.set_ylim([0, 1.02])
                plt.tight_layout()
                path = os.path.join(output_dir, 'roc_curve.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ ROC Curve → {path}")
            except Exception as e:
                print(f"   ⚠️ ROC Curve failed: {e}")
        
        # --- 6. PRECISION-RECALL CURVE (binary) ---
        if y_proba is not None and is_binary:
            try:
                proba_pos = y_proba[:, 1] if y_proba.ndim == 2 else y_proba
                precision_vals, recall_vals, _ = precision_recall_curve(y_test, proba_pos)
                ap = average_precision_score(y_test, proba_pos)
                fig, ax = plt.subplots(figsize=(8, 6))
                ax.plot(recall_vals, precision_vals, color='#059669', lw=2,
                       label=f'AP = {ap:.4f}')
                ax.set_xlabel('Recall')
                ax.set_ylabel('Precision')
                ax.set_title('Precision-Recall Curve')
                ax.legend(loc='lower left')
                ax.set_xlim([0, 1])
                ax.set_ylim([0, 1.02])
                plt.tight_layout()
                path = os.path.join(output_dir, 'precision_recall.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Precision-Recall → {path}")
            except Exception as e:
                print(f"   ⚠️ Precision-Recall failed: {e}")
        
        # --- 7. CALIBRATION CURVE (binary) ---
        if y_proba is not None and is_binary and HAS_CALIBRATION and len(y_test) >= 20:
            try:
                proba_pos = y_proba[:, 1] if y_proba.ndim == 2 else y_proba
                fraction_of_positives, mean_predicted_value = calibration_curve(
                    y_test, proba_pos, n_bins=10
                )
                fig, ax = plt.subplots(figsize=(8, 6))
                ax.plot(mean_predicted_value, fraction_of_positives, 's-', color='#4F46E5',
                       label='Model', lw=2)
                ax.plot([0, 1], [0, 1], 'k--', label='Perfectly calibrated')
                ax.set_xlabel('Mean Predicted Probability')
                ax.set_ylabel('Fraction of Positives')
                ax.set_title('Calibration Curve')
                ax.legend()
                plt.tight_layout()
                path = os.path.join(output_dir, 'calibration.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Calibration Curve → {path}")
            except Exception as e:
                print(f"   ⚠️ Calibration Curve failed: {e}")
        
        # --- 8. CONFIDENCE HISTOGRAM ---
        if y_proba is not None:
            try:
                max_proba = np.max(y_proba, axis=1) if y_proba.ndim == 2 else y_proba
                correct = (y_test == y_pred)
                fig, ax = plt.subplots(figsize=(8, 5))
                ax.hist(max_proba[correct], bins=20, alpha=0.7, color='#22C55E', label='Correct', edgecolor='white')
                ax.hist(max_proba[~correct], bins=20, alpha=0.7, color='#EF4444', label='Incorrect', edgecolor='white')
                ax.set_xlabel('Prediction Confidence')
                ax.set_ylabel('Count')
                ax.set_title('Confidence Distribution: Correct vs Incorrect')
                ax.legend()
                plt.tight_layout()
                path = os.path.join(output_dir, 'confidence_histogram.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Confidence Histogram → {path}")
            except Exception as e:
                print(f"   ⚠️ Confidence Histogram failed: {e}")
        
        # --- 9. METRICS HEATMAP (per-class precision/recall/f1) ---
        if n_classes <= 10:
            try:
                labels = class_names if class_names else sorted(np.unique(y_test).tolist())
                prec_per_class = precision_score(y_test, y_pred, average=None, zero_division=0)
                rec_per_class = recall_score(y_test, y_pred, average=None, zero_division=0)
                f1_per_class = f1_score(y_test, y_pred, average=None, zero_division=0)
                
                metrics_df = pd.DataFrame({
                    'Precision': prec_per_class[:len(labels)],
                    'Recall': rec_per_class[:len(labels)],
                    'F1-Score': f1_per_class[:len(labels)],
                }, index=labels[:len(prec_per_class)])
                
                fig, ax = plt.subplots(figsize=(8, max(3, len(labels) * 0.5)))
                sns.heatmap(metrics_df, annot=True, fmt='.3f', cmap='YlGn', ax=ax,
                           vmin=0, vmax=1, linewidths=0.5)
                ax.set_title('Per-Class Metrics Heatmap')
                plt.tight_layout()
                path = os.path.join(output_dir, 'metrics_heatmap.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Metrics Heatmap → {path}")
            except Exception as e:
                print(f"   ⚠️ Metrics Heatmap failed: {e}")
        
        # --- 10. CLASS BALANCE PIE CHART (actual vs predicted) ---
        try:
            fig, axes = plt.subplots(1, 2, figsize=(12, 5))
            labels = class_names if class_names else sorted(np.unique(y_test).tolist())
            actual_counts = pd.Series(y_test).value_counts().sort_index()
            pred_counts = pd.Series(y_pred).value_counts().sort_index()
            colors_pie = sns.color_palette('Set2', len(labels))
            axes[0].pie(actual_counts.values, labels=[str(l)[:15] for l in labels],
                       autopct='%1.1f%%', colors=colors_pie,
                       wedgeprops={'edgecolor': 'white'})
            axes[0].set_title('Actual Class Balance')
            axes[1].pie(pred_counts.reindex(actual_counts.index, fill_value=0).values,
                       labels=[str(l)[:15] for l in labels],
                       autopct='%1.1f%%', colors=colors_pie,
                       wedgeprops={'edgecolor': 'white'})
            axes[1].set_title('Predicted Class Balance')
            plt.suptitle('Class Balance: Actual vs Predicted', fontsize=14)
            plt.tight_layout()
            path = os.path.join(output_dir, 'class_balance_pie.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Class Balance Pie → {path}")
        except Exception as e:
            print(f"   ⚠️ Class Balance Pie failed: {e}")
        
        # --- 11. CONFIDENCE BOX PLOT BY CLASS ---
        if y_proba is not None:
            try:
                fig, ax = plt.subplots(figsize=(10, 6))
                max_proba = np.max(y_proba, axis=1) if y_proba.ndim == 2 else y_proba
                classes = sorted(np.unique(y_test).tolist())
                data_boxes = [max_proba[y_test == c] for c in classes]
                bp = ax.boxplot(data_boxes, patch_artist=True)
                box_colors = sns.color_palette('Set2', len(classes))
                for i, patch in enumerate(bp['boxes']):
                    patch.set_facecolor(box_colors[i % len(box_colors)])
                    patch.set_alpha(0.7)
                labels = [str(class_names[i])[:15] if class_names and i < len(class_names) else str(c) for i, c in enumerate(classes)]
                ax.set_xticklabels(labels, rotation=45, ha='right')
                ax.set_xlabel('Class')
                ax.set_ylabel('Prediction Confidence')
                ax.set_title('Confidence Distribution by Class')
                plt.tight_layout()
                path = os.path.join(output_dir, 'confidence_boxplot.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Confidence Boxplot → {path}")
            except Exception as e:
                print(f"   ⚠️ Confidence Boxplot failed: {e}")
        
        # --- 12. SCORE DISTRIBUTION (KDE per class) ---
        if y_proba is not None and y_proba.ndim == 2:
            try:
                fig, ax = plt.subplots(figsize=(10, 6))
                for i in range(min(y_proba.shape[1], 5)):
                    label = str(class_names[i])[:15] if class_names and i < len(class_names) else f'Class {i}'
                    try:
                        sns.kdeplot(y_proba[:, i], ax=ax, label=label, lw=2)
                    except:
                        ax.hist(y_proba[:, i], bins=30, alpha=0.5, label=label, density=True)
                ax.set_xlabel('Prediction Score')
                ax.set_ylabel('Density')
                ax.set_title('Score Distribution by Class')
                ax.legend()
                plt.tight_layout()
                path = os.path.join(output_dir, 'score_distribution.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Score Distribution → {path}")
            except Exception as e:
                print(f"   ⚠️ Score Distribution failed: {e}")
    
    # =====================================================================
    # REGRESSION-SPECIFIC CHARTS
    # =====================================================================
    if not is_clf and y_test is not None and y_pred is not None:
        
        # --- 3. ACTUAL VS PREDICTED ---
        try:
            r2 = r2_score(y_test, y_pred)
            mae = mean_absolute_error(y_test, y_pred)
            rmse = np.sqrt(mean_squared_error(y_test, y_pred))
            
            fig, ax = plt.subplots(figsize=(8, 8))
            ax.scatter(y_test, y_pred, alpha=0.5, color='#3B82F6', edgecolors='white', s=50)
            lims = [min(y_test.min(), y_pred.min()), max(y_test.max(), y_pred.max())]
            ax.plot(lims, lims, '--', color='#EF4444', linewidth=2, label='Perfect')
            ax.set_title(f'Actual vs Predicted — R²={r2:.4f}, MAE={mae:.4f}, RMSE={rmse:.4f}')
            ax.set_xlabel('Actual')
            ax.set_ylabel('Predicted')
            ax.legend()
            plt.tight_layout()
            path = os.path.join(output_dir, 'actual_vs_predicted.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Actual vs Predicted → {path}")
        except Exception as e:
            print(f"   ⚠️ Actual vs Predicted failed: {e}")
        
        # --- 4. RESIDUALS ANALYSIS (2x2 grid) ---
        try:
            residuals = y_test - y_pred
            fig, axes = plt.subplots(2, 2, figsize=(12, 10))
            # Residuals vs Predicted
            axes[0, 0].scatter(y_pred, residuals, alpha=0.5, color='#8B5CF6', s=30)
            axes[0, 0].axhline(y=0, color='#EF4444', linestyle='--', linewidth=2)
            axes[0, 0].set_title('Residuals vs Predicted')
            axes[0, 0].set_xlabel('Predicted'); axes[0, 0].set_ylabel('Residuals')
            # Histogram
            axes[0, 1].hist(residuals, bins=30, color='#06B6D4', edgecolor='white', alpha=0.8)
            axes[0, 1].set_title('Residual Distribution')
            axes[0, 1].set_xlabel('Residual'); axes[0, 1].set_ylabel('Frequency')
            # Q-Q plot
            sorted_res = np.sort(residuals)
            n = len(sorted_res)
            theoretical = np.random.normal(0, 1, n)
            theoretical.sort()
            axes[1, 0].scatter(theoretical, sorted_res, alpha=0.5, color='#F59E0B', s=20)
            lims = [min(theoretical.min(), sorted_res.min()), max(theoretical.max(), sorted_res.max())]
            axes[1, 0].plot(lims, lims, 'r--')
            axes[1, 0].set_title('Q-Q Plot')
            axes[1, 0].set_xlabel('Theoretical Quantiles'); axes[1, 0].set_ylabel('Sample Quantiles')
            # Residuals vs Index
            axes[1, 1].plot(range(len(residuals)), residuals, 'o', alpha=0.5, color='#10B981', markersize=4)
            axes[1, 1].axhline(y=0, color='#EF4444', linestyle='--')
            axes[1, 1].set_title('Residuals vs Index')
            axes[1, 1].set_xlabel('Sample Index'); axes[1, 1].set_ylabel('Residual')
            plt.suptitle('Residuals Analysis', fontsize=14)
            plt.tight_layout()
            path = os.path.join(output_dir, 'residuals_analysis.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Residuals Analysis → {path}")
        except Exception as e:
            print(f"   ⚠️ Residuals Analysis failed: {e}")
        
        # --- 5. ERROR DISTRIBUTION ---
        try:
            abs_errors = np.abs(y_test - y_pred)
            fig, ax = plt.subplots(figsize=(8, 5))
            ax.hist(abs_errors, bins=30, color='#F97316', edgecolor='white', alpha=0.8, density=True)
            p50 = np.percentile(abs_errors, 50)
            p90 = np.percentile(abs_errors, 90)
            p95 = np.percentile(abs_errors, 95)
            ax.axvline(p50, color='green', linestyle='--', label=f'Median: {p50:.3f}')
            ax.axvline(p90, color='orange', linestyle='--', label=f'P90: {p90:.3f}')
            ax.axvline(p95, color='red', linestyle='--', label=f'P95: {p95:.3f}')
            ax.set_title('Absolute Error Distribution')
            ax.set_xlabel('Absolute Error')
            ax.set_ylabel('Density')
            ax.legend()
            plt.tight_layout()
            path = os.path.join(output_dir, 'error_distribution.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Error Distribution → {path}")
        except Exception as e:
            print(f"   ⚠️ Error Distribution failed: {e}")
        
        # --- 6. PREDICTION OVERVIEW (sorted with ±2sigma) ---
        try:
            idx_sorted = np.argsort(y_test)
            fig, ax = plt.subplots(figsize=(10, 5))
            ax.plot(range(len(y_test)), y_test[idx_sorted], 'o', color='#3B82F6', markersize=3, label='Actual', alpha=0.7)
            ax.plot(range(len(y_pred)), y_pred[idx_sorted], 'x', color='#EF4444', markersize=3, label='Predicted', alpha=0.7)
            residuals_sorted = y_test[idx_sorted] - y_pred[idx_sorted]
            sigma = np.std(residuals_sorted)
            ax.fill_between(range(len(y_test)), y_pred[idx_sorted] - 2*sigma, y_pred[idx_sorted] + 2*sigma,
                           alpha=0.15, color='red', label=f'±2σ ({sigma:.3f})')
            ax.set_title('Prediction Overview (Sorted)')
            ax.set_xlabel('Sorted Sample Index')
            ax.set_ylabel('Value')
            ax.legend()
            plt.tight_layout()
            path = os.path.join(output_dir, 'prediction_overview.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Prediction Overview → {path}")
        except Exception as e:
            print(f"   ⚠️ Prediction Overview failed: {e}")
        
        # --- 7. ERROR BOX PLOT BY QUANTILES ---
        try:
            abs_errors = np.abs(y_test - y_pred)
            quantiles = np.percentile(y_test, [0, 25, 50, 75, 100])
            groups = []
            q_labels = []
            for qi in range(len(quantiles) - 1):
                mask = (y_test >= quantiles[qi]) & (y_test < quantiles[qi+1])
                if mask.sum() > 0:
                    groups.append(abs_errors[mask])
                    q_labels.append(f'Q{qi+1}')
            if groups:
                fig, ax = plt.subplots(figsize=(10, 6))
                bp = ax.boxplot(groups, patch_artist=True)
                box_colors = ['#3B82F6', '#22C55E', '#F59E0B', '#EF4444']
                for i, patch in enumerate(bp['boxes']):
                    patch.set_facecolor(box_colors[i % len(box_colors)])
                    patch.set_alpha(0.7)
                ax.set_xticklabels(q_labels)
                ax.set_xlabel('Target Quantile')
                ax.set_ylabel('Absolute Error')
                ax.set_title('Error Distribution by Target Range')
                plt.tight_layout()
                path = os.path.join(output_dir, 'error_boxplot.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Error Boxplot → {path}")
        except Exception as e:
            print(f"   ⚠️ Error Boxplot failed: {e}")
        
        # --- 8. SCALE-LOCATION PLOT ---
        try:
            residuals_sl = y_test - y_pred
            sqrt_abs_resid = np.sqrt(np.abs(residuals_sl))
            fig, ax = plt.subplots(figsize=(8, 6))
            ax.scatter(y_pred, sqrt_abs_resid, alpha=0.5, color='#8B5CF6', s=30)
            z = np.polyfit(y_pred, sqrt_abs_resid, 1)
            p = np.poly1d(z)
            ax.plot(np.sort(y_pred), p(np.sort(y_pred)), 'r--', lw=2)
            ax.set_xlabel('Fitted Values')
            ax.set_ylabel('√|Residuals|')
            ax.set_title('Scale-Location Plot')
            plt.tight_layout()
            path = os.path.join(output_dir, 'scale_location.png')
            plt.savefig(path, dpi=150, bbox_inches='tight')
            plt.close()
            charts.append(path)
            print(f"   ✅ Scale-Location → {path}")
        except Exception as e:
            print(f"   ⚠️ Scale-Location failed: {e}")
    
    # =====================================================================
    # DATA EXPLORATION CHARTS (both classification & regression)
    # =====================================================================
    if df is not None:
        y = df[target_col] if target_col in df.columns else None
        
        # --- 10. CORRELATION HEATMAP ---
        try:
            numeric_df = df.select_dtypes(include=[np.number])
            if len(numeric_df.columns) >= 2:
                corr = numeric_df.corr()
                fig, ax = plt.subplots(figsize=(min(14, len(corr) + 2), min(12, len(corr) + 1)))
                mask = np.triu(np.ones_like(corr, dtype=bool))
                sns.heatmap(corr, mask=mask, annot=len(corr) <= 15, fmt='.2f',
                           cmap='RdBu_r', center=0, ax=ax, square=True, linewidths=0.5)
                ax.set_title('Feature Correlation Heatmap')
                plt.tight_layout()
                path = os.path.join(output_dir, 'correlation_heatmap.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Correlation Heatmap → {path}")
        except Exception as e:
            print(f"   ⚠️ Correlation Heatmap failed: {e}")
        
        # --- 11. FEATURE DISTRIBUTIONS ---
        try:
            plot_cols = NUMERIC_FEATURES if NUMERIC_FEATURES else df.select_dtypes(include=[np.number]).columns[:9].tolist()
            cols_to_plot = [c for c in plot_cols if c in df.columns][:9]
            if cols_to_plot:
                ncols = min(3, len(cols_to_plot))
                nrows = (len(cols_to_plot) + ncols - 1) // ncols
                fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 4 * nrows))
                if nrows * ncols == 1:
                    axes = np.array([axes])
                axes = axes.flatten()
                for i, col in enumerate(cols_to_plot):
                    axes[i].hist(df[col].dropna(), bins=30, color='#4F46E5', edgecolor='white', alpha=0.8)
                    axes[i].set_title(col, fontsize=10)
                    axes[i].tick_params(labelsize=8)
                for i in range(len(cols_to_plot), len(axes)):
                    axes[i].set_visible(False)
                plt.suptitle('Feature Distributions', fontsize=14)
                plt.tight_layout()
                path = os.path.join(output_dir, 'distribution_grid.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Distribution Grid → {path}")
        except Exception as e:
            print(f"   ⚠️ Distribution Grid failed: {e}")
        
        # --- 12. BOXPLOT GRID ---
        try:
            plot_cols = NUMERIC_FEATURES if NUMERIC_FEATURES else df.select_dtypes(include=[np.number]).columns[:9].tolist()
            cols_to_plot = [c for c in plot_cols if c in df.columns][:9]
            if cols_to_plot:
                ncols = min(3, len(cols_to_plot))
                nrows = (len(cols_to_plot) + ncols - 1) // ncols
                fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 4 * nrows))
                if nrows * ncols == 1:
                    axes = np.array([axes])
                axes = axes.flatten()
                colors = sns.color_palette('Set2', len(cols_to_plot))
                for i, col in enumerate(cols_to_plot):
                    axes[i].boxplot(df[col].dropna(), patch_artist=True,
                                   boxprops=dict(facecolor=colors[i], alpha=0.7))
                    axes[i].set_title(col, fontsize=10)
                    axes[i].tick_params(labelsize=8)
                for i in range(len(cols_to_plot), len(axes)):
                    axes[i].set_visible(False)
                plt.suptitle('Feature Boxplots (Outlier Detection)', fontsize=14)
                plt.tight_layout()
                path = os.path.join(output_dir, 'boxplot_grid.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Boxplot Grid → {path}")
        except Exception as e:
            print(f"   ⚠️ Boxplot Grid failed: {e}")
        
        # --- 13. TARGET DISTRIBUTION (from raw data) ---
        if y is not None:
            try:
                fig, ax = plt.subplots(figsize=(8, 5))
                if is_clf:
                    y.value_counts().plot(kind='bar', ax=ax, color=sns.color_palette('Set2'))
                    ax.set_ylabel('Count')
                else:
                    ax.hist(y.dropna(), bins=30, color='#06B6D4', edgecolor='white', alpha=0.8)
                    ax.set_ylabel('Frequency')
                ax.set_title(f'Target Distribution: price_range')
                ax.set_xlabel('price_range')
                plt.xticks(rotation=45, ha='right')
                plt.tight_layout()
                path = os.path.join(output_dir, 'target_distribution.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Target Distribution → {path}")
            except Exception as e:
                print(f"   ⚠️ Target Distribution failed: {e}")
        
        # =====================================================================
        # UNSUPERVISED LEARNING — Auto Clustering (KMeans)
        # =====================================================================
        try:
            from sklearn.cluster import KMeans
            from sklearn.preprocessing import StandardScaler as ClusterScaler
            from sklearn.decomposition import PCA
            from sklearn.metrics import silhouette_score as sil_score
            
            numeric_df = df.select_dtypes(include=[np.number]).dropna()
            if len(numeric_df) >= 10 and len(numeric_df.columns) >= 2:
                # Scale for clustering
                c_scaler = ClusterScaler()
                X_clust = c_scaler.fit_transform(numeric_df)
                
                # Find optimal k using silhouette score
                best_k = 3
                best_sil = -1
                for k in range(2, min(8, len(numeric_df))):
                    try:
                        km = KMeans(n_clusters=k, random_state=42, n_init=10)
                        labels_k = km.fit_predict(X_clust)
                        sil_k = sil_score(X_clust, labels_k)
                        if sil_k > best_sil:
                            best_sil = sil_k
                            best_k = k
                    except:
                        pass
                
                # Run clustering with best k
                km_final = KMeans(n_clusters=best_k, random_state=42, n_init=10)
                labels = km_final.fit_predict(X_clust)
                
                # PCA for 2D visualization
                pca = PCA(n_components=2)
                X_2d = pca.fit_transform(X_clust)
                
                # --- Cluster Scatter Plot ---
                fig, ax = plt.subplots(figsize=(10, 8))
                colors_clust = ['#2563eb', '#16a34a', '#dc2626', '#ea580c', '#9333ea',
                               '#0891b2', '#db2777', '#d97706', '#0d9488', '#4f46e5']
                for i in range(best_k):
                    mask = labels == i
                    ax.scatter(X_2d[mask, 0], X_2d[mask, 1],
                              c=colors_clust[i % len(colors_clust)],
                              label=f'Cluster {i}', alpha=0.7, s=50,
                              edgecolors='white', linewidth=0.5)
                ax.set_xlabel('PCA Component 1', fontweight='bold')
                ax.set_ylabel('PCA Component 2', fontweight='bold')
                ax.set_title(f'KMeans Clustering (k={best_k}, Silhouette={best_sil:.3f})',
                            fontweight='bold', pad=15, fontsize=14)
                ax.legend(loc='best')
                ax.grid(alpha=0.3)
                plt.tight_layout()
                path = os.path.join(output_dir, 'cluster_scatter.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Cluster Scatter → {path}")
                
                # --- Cluster Distribution Bar Chart ---
                fig, ax = plt.subplots(figsize=(8, 5))
                unique, counts = np.unique(labels, return_counts=True)
                ax.bar([f'Cluster {u}' for u in unique], counts,
                      color=[colors_clust[u % len(colors_clust)] for u in unique],
                      edgecolor='white')
                ax.set_xlabel('Cluster')
                ax.set_ylabel('Count')
                ax.set_title('Cluster Size Distribution')
                for i, (u, c) in enumerate(zip(unique, counts)):
                    ax.text(i, c + 0.5, str(c), ha='center', fontsize=10)
                plt.tight_layout()
                path = os.path.join(output_dir, 'cluster_distribution.png')
                plt.savefig(path, dpi=150, bbox_inches='tight')
                plt.close()
                charts.append(path)
                print(f"   ✅ Cluster Distribution → {path}")
        except Exception as e:
            print(f"   ⚠️ Clustering charts failed: {e}")
    
    print(f"\n📊 Generated {len(charts)} charts in '{output_dir}/'")
    return charts


def main():
    parser = argparse.ArgumentParser(description="Generate charts from your trained model")
    parser.add_argument('--model', type=str, default='model.pkl', help='Path to traditional ML model')
    parser.add_argument('--dl-model', type=str, default='deep_learning_model.pkl', help='Path to DL model')
    parser.add_argument('--mode', type=str, default='auto', choices=['auto', 'traditional', 'dl'],
                       help='Which model to visualize (auto uses BEST_MODE)')
    parser.add_argument('--data', type=str, default='data/cleaned_data.csv')
    parser.add_argument('--output', type=str, default='charts')
    args = parser.parse_args()
    
    print("\n" + "=" * 60)
    print("📊 DataVision Chart Generator")
    print("=" * 60)
    
    # Decide which model to load based on BEST_MODE
    use_dl = False
    state = None
    df = None
    
    if args.mode == 'dl' or (args.mode == 'auto' and BEST_MODE == 'deep_learning'):
        state = load_dl_model(args.dl_model)
        if state:
            use_dl = True
        else:
            print("⚠️ DL model not found, falling back to traditional ML model...")
    
    if not use_dl and args.mode != 'dl':
        state, df = load_model_and_data(args.model, args.data)
        if state is None and os.path.exists(args.dl_model):
            state = load_dl_model(args.dl_model)
            if state:
                use_dl = True
    
    if state is None:
        print("❌ No model found. Provide model.pkl or deep_learning_model.pkl")
        return
    
    # Load data if not yet loaded
    if df is None:
        data_path = args.data
        df = pd.read_csv(data_path) if os.path.exists(data_path) else None
    
    mode_display = 'deep_learning' if use_dl else state.get('mode', 'traditional')
    model_name = state.get('model_name', state.get('algorithm', 'Unknown'))
    
    print(f"\n🏆 Model: {model_name}")
    print(f"📊 Mode: {mode_display}")
    print(f"🎯 Task: {state.get('task_type', TASK_TYPE)}")
    if use_dl:
        print(f"🧠 Architecture: {state.get('algorithm', 'MLP')}")
    if df is not None:
        print(f"📋 Data: {len(df)} rows, {len(df.columns)} columns")
    
    generate_charts(state, df, args.output)
    print(f"\n✅ Done! Open '{args.output}/' to view charts.")


if __name__ == '__main__':
    main()
