import React, { useState, useEffect } from 'react';
import { useUserStore } from '@/store/userStore';
import apiService from '@/services/api';
import ScenarioCard from './ScenarioCard';
import { Brain, Plus, RefreshCcw } from 'lucide-react';

const AISuggestedScenariosTab: React.FC = () => {
  const { isDark } = useUserStore();
  const [scenarios, setScenarios] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const textPrimary = isDark ? '#f8fafc' : '#0f172a';
  const textMuted = isDark ? '#94a3b8' : '#64748b';
  const cardBg = isDark ? 'rgba(255,255,255,0.03)' : '#ffffff';
  const cardBorder = isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)';

  const fetchScenarios = async () => {
    setLoading(true);
    try {
      const res = await apiService.getSuggestedScenarios();
      setScenarios(res.data?.scenarios || []);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchScenarios(); }, []);

  const handleRun = async (id: string) => {
    const scenario = scenarios.find(s => s.id === id);
    if (scenario) {
      try {
        await apiService.saveScenario({
          name: scenario.title,
          description: scenario.goal,
          variables: {},
          tags: scenario.tags,
        });
      } catch {}
    }
  };

  if (loading) return <div className="flex items-center justify-center h-96"><div className="w-8 h-8 border-3 border-indigo-500 border-t-transparent rounded-full animate-spin" /></div>;

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-bold flex items-center gap-2" style={{ color: textPrimary }}>
          <Brain className="w-4 h-4 text-indigo-400" /> AI-Generated Scenario Recommendations
        </h3>
        <div className="flex items-center gap-2">
          <button onClick={fetchScenarios} className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs hover:bg-white/5" style={{ borderColor: cardBorder, color: textMuted }}>
            <RefreshCcw className="w-3.5 h-3.5" /> Regenerate
          </button>
          <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-medium shadow-sm shadow-indigo-600/20">
            <Plus className="w-3.5 h-3.5" /> Custom Goal
          </button>
        </div>
      </div>

      {/* Info Banner */}
      <div className="rounded-xl p-4 border-l-4" style={{
        background: isDark ? 'rgba(99,102,241,0.05)' : 'rgba(99,102,241,0.03)',
        borderLeftColor: '#6366f1',
      }}>
        <p className="text-xs leading-relaxed" style={{ color: isDark ? '#cbd5e1' : '#475569' }}>
          🤖 These scenarios are generated by analyzing your dataset correlations, feature importance, and historical simulation patterns.
          Each scenario optimizes for a specific business objective.
        </p>
      </div>

      {/* Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        {scenarios.map((s) => (
          <ScenarioCard
            key={s.id}
            id={s.id}
            name={s.name}
            title={s.title}
            goal={s.goal}
            tags={s.tags}
            badge={s.badge}
            badgeColor={s.badge_color}
            metrics={s.metrics}
            confidence={s.confidence}
            estimatedRoi={s.estimated_roi}
            runtimeMs={s.runtime_ms}
            onRun={handleRun}
          />
        ))}
      </div>

      {scenarios.length === 0 && (
        <div className="text-center py-16">
          <Brain className="w-12 h-12 mx-auto mb-3" style={{ color: textMuted }} />
          <p className="text-sm" style={{ color: textMuted }}>No AI-suggested scenarios available yet</p>
          <p className="text-xs mt-1" style={{ color: textMuted }}>Upload data and train a model to enable AI suggestions</p>
        </div>
      )}
    </div>
  );
};

export default AISuggestedScenariosTab;
