"""
🔮 Prediction Script — Uses Your ACTUAL Trained Model
========================================================
Auto-generated by DataVision AI

╔════════════════════════════════════════════════════════════════════╗
║  This script loads YOUR model.pkl that was trained by AutoML.     ║
║  The predictions match EXACTLY what you saw in DataVision.        ║
╚════════════════════════════════════════════════════════════════════╝

YOUR MODEL:
    🏆 Model     : RandomForest
    🎯 Target    : price_range
    📊 Task      : classification
    📁 Features  : 20 columns

Usage:
    python predict.py                                    # Interactive mode
    python predict.py --json '{"col1": 1, "col2": "A"}'  # JSON input
    python predict.py --csv input.csv                    # Batch predictions
"""

import os
import pickle
import argparse
import json
import re
import warnings
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, RobustScaler

warnings.filterwarnings('ignore')

# Your actual feature columns from training
FEATURE_COLUMNS = ['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g', 'touch_screen', 'wifi']
TARGET_COLUMN = 'price_range'
BEST_MODE = 'traditional'  # Which mode won during AutoML

# Feature metadata with actual types and ranges from your dataset
FEATURE_INFO = {
        "battery_power": {"type": "numeric", "min": 510.0, "max": 1987.0, "default": 1238.51},
        "blue": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.49},
        "clock_speed": {"type": "numeric", "min": 0.5, "max": 3.0, "default": 1.52},
        "dual_sim": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.51},
        "fc": {"type": "numeric", "min": 0.0, "max": 16.0, "default": 4.29},
        "four_g": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.52},
        "int_memory": {"type": "numeric", "min": 2.0, "max": 64.0, "default": 32.05},
        "m_dep": {"type": "numeric", "min": 0.1, "max": 1.0, "default": 0.50},
        "mobile_wt": {"type": "numeric", "min": 80.0, "max": 199.0, "default": 140.24},
        "n_cores": {"type": "numeric", "min": 1.0, "max": 8.0, "default": 4.52},
        "pc": {"type": "numeric", "min": 0.0, "max": 20.0, "default": 9.92},
        "px_height": {"type": "numeric", "min": 15.0, "max": 1791.01, "default": 644.46},
        "ram": {"type": "numeric", "min": 296.99, "max": 3958.01, "default": 2124.26},
        "sc_h": {"type": "numeric", "min": 5.0, "max": 19.0, "default": 12.31},
        "sc_w": {"type": "numeric", "min": 0.0, "max": 17.0, "default": 5.76},
        "three_g": {"type": "numeric", "min": 1.0, "max": 1.0, "default": 1.00},
        "touch_screen": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.50},
        "wifi": {"type": "numeric", "min": 0.0, "max": 1.0, "default": 0.51},
}


# =============================================================================
# Standalone Feature Engineer — Replicates DataVision's EXACT preprocessing
# =============================================================================
class StandaloneFeatureEngineer:
    """Replicate DataVision's ProductionFeatureEngineer.transform() pipeline.
    
    Loaded from feature_engineer.pkl which contains all fitted sklearn
    transformers, encoders, and feature names from your AutoML training.
    """
    
    def __init__(self, state):
        self.transformers = state.get('transformers', {})
        self.encoders = state.get('encoders', {})
        self.feature_names = state.get('feature_names', [])
        self.original_columns = state.get('original_columns', [])
        self.selected_feature_indices = state.get('selected_feature_indices', None)
        self.is_fitted = state.get('is_fitted', True)
        # Stopwords / sentiment words for text features
        self.stopwords = set("i me my myself we our ours ourselves you your yours yourself yourselves he him his himself she her hers herself it its itself they them their theirs themselves what which who whom this that these those am is are was were be been being have has had having do does did doing a an the and but if or because as until while of at by for with about against between through during before after above below to from up down in out on off over under again further then once here there when where why how all both each few more most other some such no nor not only own same so than too very s t can will just don should now d ll m o re ve y ain aren couldn didn doesn hadn hasn haven isn ma mightn mustn needn shan shouldn wasn weren won wouldn".split())
        self.positive_words = set("good great excellent amazing wonderful fantastic brilliant outstanding superb love best perfect beautiful awesome incredible impressive magnificent exceptional fabulous terrific marvelous stellar remarkable extraordinary delightful gorgeous splendid spectacular phenomenal exquisite lovely charming pleasant nice fine happy joy enjoy satisfied pleased glad cheerful excited thrilled".split())
        self.negative_words = set("bad terrible horrible awful worst poor disappointing disgusting pathetic useless dreadful atrocious appalling abysmal mediocre inferior unpleasant nasty vile wretched miserable lousy horrendous hideous ghastly hideous deplorable lamentable pitiful woeful tragic sad angry frustrated annoyed irritated disappointed upset unhappy distressed sorrowful gloomy depressed".split())
    
    def _clean_text(self, text):
        text = str(text).lower()
        text = re.sub(r'<[^>]+>', ' ', text)
        text = re.sub(r'http\S+', ' ', text)
        text = re.sub(r'[^a-z0-9\s]', ' ', text)
        text = ' '.join(w for w in text.split() if w not in self.stopwords and len(w) > 1)
        return text if text.strip() else 'empty'
    
    def _text_statistics(self, text):
        text = str(text)
        words = text.split()
        word_lengths = [len(w) for w in words] if words else [0]
        unique_ratio = len(set(words)) / max(len(words), 1)
        features = [
            len(text), len(words), np.mean(word_lengths), np.std(word_lengths),
            np.max(word_lengths) if word_lengths else 0, unique_ratio,
            text.count('!'), text.count('?'),
            sum(1 for c in text if c.isupper()) / max(len(text), 1),
            len([w for w in words if len(w) > 6]) / max(len(words), 1),
        ]
        return features
    
    def _sentiment_score(self, text):
        words = set(str(text).lower().split())
        pos = len(words & self.positive_words)
        neg = len(words & self.negative_words)
        total = max(pos + neg, 1)
        return [pos / total, neg / total, (pos - neg) / total, total]
    
    def transform(self, df):
        if not self.is_fitted:
            raise ValueError("Feature engineer not fitted!")
        df = df.copy()
        
        # Handle duplicate column names
        cols = df.columns.tolist()
        seen = {}
        new_cols = []
        for col in cols:
            if col in seen:
                seen[col] += 1
                new_cols.append(f"{col}_{seen[col]}")
            else:
                seen[col] = 0
                new_cols.append(col)
        df.columns = new_cols
        
        feature_parts = []
        
        # ===== NUMERIC FEATURES =====
        if 'numeric_cols' in self.transformers:
            numeric_cols = self.transformers['numeric_cols']
            for col in numeric_cols:
                if col not in df.columns:
                    df[col] = 0
            try:
                numeric_data = df[numeric_cols].apply(pd.to_numeric, errors='coerce').fillna(0).values
                scaler = self.transformers['numeric_scaler']
                numeric_scaled = scaler.transform(numeric_data)
                numeric_scaled = np.nan_to_num(numeric_scaled, nan=0.0, posinf=0.0, neginf=0.0)
                feature_parts.append(numeric_scaled)
                
                # Polynomial features
                if 2 <= len(numeric_cols) <= 10:
                    interactions = []
                    for i in range(min(len(numeric_cols), 4)):
                        interactions.append((numeric_scaled[:, i] ** 2).reshape(-1, 1))
                    for i in range(min(len(numeric_cols), 4)):
                        for j in range(i + 1, min(len(numeric_cols), 4)):
                            interactions.append((numeric_scaled[:, i] * numeric_scaled[:, j]).reshape(-1, 1))
                    if interactions:
                        feature_parts.append(np.hstack(interactions))
            except Exception as e:
                print(f"   Warning: Numeric transform error: {e}")
                feature_parts.append(np.zeros((len(df), len(numeric_cols))))
        
        # ===== CATEGORICAL: One-hot =====
        for key, cols in self.transformers.items():
            if key.endswith('_onehot'):
                col_name = key.replace('_onehot', '')
                try:
                    if col_name in df.columns:
                        series = df[col_name].fillna('_MISSING_').astype(str).str.strip()
                        dummies = pd.get_dummies(series, prefix=col_name)
                        dummies = dummies.reindex(columns=cols, fill_value=0)
                        feature_parts.append(dummies.values.astype(float))
                    else:
                        feature_parts.append(np.zeros((len(df), len(cols))))
                except:
                    feature_parts.append(np.zeros((len(df), len(cols))))
        
        # ===== CATEGORICAL: Label + Frequency =====
        for col, le in self.encoders.items():
            try:
                if col in df.columns:
                    series = df[col].fillna('_MISSING_').astype(str).str.strip()
                    encoded = series.map(lambda s: le.transform([s])[0] if s in le.classes_ else -1)
                    feature_parts.append(encoded.values.reshape(-1, 1).astype(float))
                    freq_key = f'{col}_freq_map'
                    if freq_key in self.transformers:
                        freq_map = self.transformers[freq_key]
                        freq_encoded = series.map(lambda s: freq_map.get(s, 0.0)).values.astype(float)
                        feature_parts.append(freq_encoded.reshape(-1, 1))
                else:
                    feature_parts.append(np.zeros((len(df), 1)))
                    if f'{col}_freq_map' in self.transformers:
                        feature_parts.append(np.zeros((len(df), 1)))
            except:
                feature_parts.append(np.zeros((len(df), 1)))
        
        # ===== CATEGORICAL INTERACTIONS =====
        if 'cat_interactions' in self.transformers:
            interaction_encoders = self.transformers['cat_interactions']
            for key, value in interaction_encoders.items():
                if key.endswith('_freq_map'):
                    continue
                try:
                    col1, col2, le = value
                    if col1 in df.columns and col2 in df.columns:
                        combined = df[col1].fillna('_NA_').astype(str) + "_X_" + df[col2].fillna('_NA_').astype(str)
                        encoded = combined.map(lambda s: le.transform([s])[0] if s in le.classes_ else -1)
                        feature_parts.append(encoded.values.reshape(-1, 1).astype(float))
                        freq_key = f"{key}_freq_map"
                        if freq_key in interaction_encoders:
                            freq_map = interaction_encoders[freq_key]
                            freq_encoded = combined.map(lambda s: freq_map.get(s, 0.0)).values.astype(float)
                            feature_parts.append(freq_encoded.reshape(-1, 1))
                    else:
                        feature_parts.append(np.zeros((len(df), 1)))
                        if f"{key}_freq_map" in interaction_encoders:
                            feature_parts.append(np.zeros((len(df), 1)))
                except:
                    pass
        
        # ===== NUMERIC-CATEGORICAL AGGREGATES =====
        if 'num_cat_aggs' in self.transformers:
            agg_maps = self.transformers['num_cat_aggs']
            for key, mean_map in agg_maps.items():
                try:
                    parts = key.rsplit('_by_', 1)
                    if len(parts) == 2:
                        num_col = parts[0]
                        cat_col = parts[1].rsplit('_mean', 1)[0]
                        if num_col in df.columns and cat_col in df.columns:
                            cat_series = df[cat_col].fillna('_NA_').astype(str)
                            default_val = np.mean(list(mean_map.values())) if mean_map else 0
                            agg_values = cat_series.map(lambda s: mean_map.get(s, default_val)).values.astype(float)
                            feature_parts.append(agg_values.reshape(-1, 1))
                            deviation = df[num_col].fillna(0).values - agg_values
                            feature_parts.append(deviation.reshape(-1, 1))
                        else:
                            feature_parts.append(np.zeros((len(df), 1)))
                            feature_parts.append(np.zeros((len(df), 1)))
                except:
                    pass
        
        # ===== TEXT / NLP FEATURES =====
        for key, tfidf in self.transformers.items():
            if key.endswith('_tfidf'):
                col = key.replace('_tfidf', '')
                try:
                    if col in df.columns:
                        series = df[col].fillna('').astype(str)
                        cleaned = series.apply(self._clean_text)
                        tfidf_matrix = tfidf.transform(cleaned)
                        svd_key = f'{col}_svd'
                        if svd_key in self.transformers:
                            text_features = self.transformers[svd_key].transform(tfidf_matrix)
                        else:
                            text_features = tfidf_matrix.toarray()
                        feature_parts.append(text_features)
                        text_stats = np.array([self._text_statistics(t) for t in series])
                        feature_parts.append(text_stats)
                        sentiment = np.array([self._sentiment_score(t) for t in series])
                        feature_parts.append(sentiment)
                except:
                    pass
        
        # ===== COMBINE =====
        if not feature_parts:
            return np.zeros((len(df), len(self.feature_names)))
        
        X = np.hstack(feature_parts)
        X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)
        
        # Variance selector
        if 'variance_selector' in self.transformers:
            selector = self.transformers['variance_selector']
            try:
                if X.shape[1] == selector.n_features_in_:
                    X = selector.transform(X)
                elif hasattr(self, 'selected_feature_indices') and self.selected_feature_indices is not None:
                    valid_idx = [i for i in self.selected_feature_indices if i < X.shape[1]]
                    if valid_idx:
                        X = X[:, valid_idx]
            except:
                pass
        
        # PCA (if used during training)
        if 'pca' in self.transformers:
            try:
                pca = self.transformers['pca']
                if X.shape[1] == pca.n_features_in_:
                    X = pca.transform(X)
            except:
                pass
        
        # Pad/truncate to match training dimensions
        if X.shape[1] != len(self.feature_names):
            if X.shape[1] < len(self.feature_names):
                padding = np.zeros((len(df), len(self.feature_names) - X.shape[1]))
                X = np.hstack([X, padding])
            else:
                X = X[:, :len(self.feature_names)]
        
        return X
    
    def transform_single(self, data):
        for col in self.original_columns:
            if col not in data:
                data[col] = 0
        df = pd.DataFrame([data])
        X = self.transform(df)
        expected = len(self.feature_names)
        if X.shape[1] != expected:
            if X.shape[1] < expected:
                X = np.hstack([X, np.zeros((1, expected - X.shape[1]))])
            else:
                X = X[:, :expected]
        return X


# =============================================================================
# Load model and feature engineer
# =============================================================================
FEATURE_ENGINEER = None

def _load_feature_engineer():
    global FEATURE_ENGINEER
    if FEATURE_ENGINEER is not None:
        return FEATURE_ENGINEER
    eng_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'feature_engineer.pkl')
    if os.path.exists(eng_path):
        try:
            with open(eng_path, 'rb') as f:
                eng_state = pickle.load(f)
            FEATURE_ENGINEER = StandaloneFeatureEngineer(eng_state)
            print(f"   Pipeline: feature_engineer.pkl ({len(FEATURE_ENGINEER.feature_names)} engineered features)")
            return FEATURE_ENGINEER
        except Exception as e:
            print(f"   Warning: Could not load feature_engineer.pkl: {e}")
    return None


def load_model(model_path='model.pkl'):
    """Load the trained model and its components."""
    if not os.path.exists(model_path):
        print(f"❌ Model not found: {model_path}")
        print("   Run the training script first, or ensure model.pkl is in this directory.")
        return None
    
    with open(model_path, 'rb') as f:
        state = pickle.load(f)
    
    print(f"✅ Loaded model: {state.get('model_name', 'Unknown')}")
    print(f"   Task: {state.get('task_type', 'Unknown')}")
    print(f"   Target: {state.get('target_column', 'Unknown')}")
    
    # Load feature engineer (exact preprocessing pipeline)
    _load_feature_engineer()
    return state


def predict_single(state, input_data: dict):
    """Make a prediction for a single data point.
    
    Uses the EXACT same preprocessing pipeline as DataVision AutoML:
    1. StandaloneFeatureEngineer from feature_engineer.pkl (preferred)
    2. Fallback to basic label-encode + scale (less accurate)
    """
    model = state['model']
    feature_cols = state.get('feature_columns', FEATURE_COLUMNS)
    target_encoder = state.get('target_encoder', None)
    task_type = state.get('task_type', 'classification')
    
    # Use feature engineer for EXACT AutoML-matching preprocessing
    engineer = _load_feature_engineer()
    if engineer is not None:
        try:
            X = engineer.transform_single(input_data)
        except Exception as e:
            print(f"Warning: Feature engineer failed ({e}), using fallback")
            X = _fallback_preprocess(input_data, state)
    else:
        X = _fallback_preprocess(input_data, state)
    
    prediction = model.predict(X)[0]
    result = {'raw_prediction': prediction}
    
    if 'classif' in task_type.lower() and target_encoder is not None:
        try:
            result['prediction'] = target_encoder.inverse_transform([int(prediction)])[0]
        except:
            result['prediction'] = prediction
    else:
        result['prediction'] = float(prediction)
    
    if 'classif' in task_type.lower() and hasattr(model, 'predict_proba'):
        try:
            proba = model.predict_proba(X)[0]
            result['confidence'] = float(max(proba))
            if target_encoder is not None:
                result['probabilities'] = {
                    str(cls): float(p) for cls, p in zip(target_encoder.classes_, proba)
                }
            else:
                result['probabilities'] = {str(i): float(p) for i, p in enumerate(proba)}
        except:
            pass
    
    return result


def _fallback_preprocess(input_data, state):
    """Fallback: basic label-encode + scale (used only if feature_engineer.pkl missing)."""
    feature_cols = state.get('feature_columns', FEATURE_COLUMNS)
    label_encoders = state.get('label_encoders', {})
    scaler = state.get('scaler', None)
    
    row = {}
    for col in feature_cols:
        val = input_data.get(col, 0)
        if col in label_encoders:
            le = label_encoders[col]
            val_str = str(val)
            val = le.transform([val_str])[0] if val_str in le.classes_ else 0
        else:
            try:
                val = float(val)
            except (ValueError, TypeError):
                val = 0
        row[col] = val
    
    X_proc = pd.DataFrame([row], columns=feature_cols)
    if scaler is not None:
        try:
            X_proc = pd.DataFrame(scaler.transform(X_proc), columns=feature_cols)
        except:
            pass
    return X_proc


def predict_batch(state, csv_path: str, output_path: str = None):
    """Make predictions for a CSV file."""
    df = pd.read_csv(csv_path)
    print(f"\n📊 Predicting for {len(df)} rows...")
    
    predictions = []
    for _, row in df.iterrows():
        result = predict_single(state, row.to_dict())
        predictions.append(result['prediction'])
    
    df['prediction'] = predictions
    if output_path is None:
        output_path = csv_path.replace('.csv', '_predictions.csv')
    df.to_csv(output_path, index=False)
    print(f"💾 Predictions saved to: {output_path}")
    return df


# =============================================================================
# Deep Learning Model Support (sklearn MLPClassifier/MLPRegressor)
# =============================================================================
DL_STATE = None

def load_dl_model(dl_path='deep_learning_model.pkl'):
    """Load the Deep Learning model (sklearn MLP) with its preprocessing state."""
    global DL_STATE
    if not os.path.exists(dl_path):
        return None
    try:
        with open(dl_path, 'rb') as f:
            DL_STATE = pickle.load(f)
        print(f"✅ Loaded DL model: {DL_STATE.get('algorithm', 'MLP')}")
        print(f"   Task: {DL_STATE.get('task_type', 'Unknown')}")
        print(f"   Features: {len(DL_STATE.get('feature_metadata', []))}")
        return DL_STATE
    except Exception as e:
        print(f"⚠️ Failed to load DL model: {e}")
        return None


def predict_single_dl(dl_state, input_data: dict):
    """Make a prediction using the Deep Learning model.
    
    Uses feature_metadata for correct preprocessing:
    - Numeric features: float conversion, fillna with mean
    - Categorical features: one-hot encoding matching training
    - StandardScaler applied to full feature vector
    """
    model = dl_state['model']
    scaler = dl_state.get('scaler')
    label_encoder = dl_state.get('label_encoder')
    feature_metadata = dl_state.get('feature_metadata', [])
    task_type = dl_state.get('task_type', 'classification')
    classes = dl_state.get('classes', [])
    
    # Build feature vector using feature_metadata (same as DL engine)
    feature_values = []
    
    # Process numeric features first
    for meta in feature_metadata:
        if meta.get('type') == 'numeric':
            col = meta['name']
            if col in input_data:
                try:
                    feature_values.append(float(input_data[col]))
                except (ValueError, TypeError):
                    feature_values.append(meta.get('mean', 0))
            else:
                feature_values.append(meta.get('mean', 0))
    
    # Process categorical features (one-hot encoded during training)
    for meta in feature_metadata:
        if meta.get('type') == 'categorical':
            col = meta['name']
            value = str(input_data.get(col, ''))
            options = meta.get('options', [])
            
            # One-hot encode: one value per option
            for opt in options:
                feature_values.append(1.0 if value == opt else 0.0)
            # NaN dummy (dummy_na=True during training)
            feature_values.append(1.0 if not value or value == 'nan' else 0.0)
    
    # Fallback to feature_columns if no metadata
    if not feature_values and dl_state.get('feature_columns'):
        for col in dl_state['feature_columns']:
            if col in input_data:
                try:
                    feature_values.append(float(input_data[col]) if not isinstance(input_data[col], str) else 0)
                except:
                    feature_values.append(0)
            else:
                feature_values.append(0)
    
    X = np.array([feature_values])
    
    # Handle dimension mismatch with scaler
    if scaler and hasattr(scaler, 'n_features_in_'):
        expected = scaler.n_features_in_
        actual = X.shape[1]
        if actual < expected:
            padding = np.zeros((1, expected - actual))
            X = np.hstack([X, padding])
        elif actual > expected:
            X = X[:, :expected]
    
    # Scale
    if scaler:
        X_scaled = scaler.transform(X)
    else:
        X_scaled = X
    
    # Predict
    pred = model.predict(X_scaled)[0]
    result = {'raw_prediction': pred}
    
    if 'classif' in task_type.lower() and label_encoder is not None:
        try:
            result['prediction'] = str(label_encoder.inverse_transform([int(pred)])[0])
        except:
            result['prediction'] = str(pred)
    else:
        result['prediction'] = float(pred)
    
    if 'classif' in task_type.lower() and hasattr(model, 'predict_proba'):
        try:
            proba = model.predict_proba(X_scaled)[0]
            result['confidence'] = float(max(proba))
            if classes:
                result['probabilities'] = {
                    str(cls): round(float(p), 4) for cls, p in zip(classes, proba)
                }
        except:
            pass
    
    return result


def interactive_mode(state, use_dl=False):
    """Interactive prediction mode with actual feature names and types."""
    print("\n" + "=" * 50)
    print("🔮 Interactive Prediction Mode")
    if use_dl:
        print("   (Using Deep Learning model)")
    print("=" * 50)
    print("Enter values for each feature:\n")
    
    # For DL mode, use feature_metadata from DL state
    if use_dl and DL_STATE:
        input_data = {}
        for meta in DL_STATE.get('feature_metadata', []):
            col = meta['name']
            ftype = meta.get('type', 'numeric')
            if ftype == 'numeric':
                mn = meta.get('min', '?')
                mx = meta.get('max', '?')
                default = meta.get('mean', 0)
                val = input(f"  {col} [{mn} - {mx}] (default: {default:.2f}): ").strip()
                input_data[col] = float(val) if val else default
            elif ftype == 'categorical':
                options = meta.get('options', [])
                print(f"  {col} options: {options}")
                val = input(f"  {col} (pick one): ").strip()
                input_data[col] = val if val else (options[0] if options else '')
        result = predict_single_dl(DL_STATE, input_data)
    else:
        input_data = {}
        for col, info in FEATURE_INFO.items():
            ftype = info.get('type', 'numeric')
            
            if ftype == 'numeric':
                mn = info.get('min', '?')
                mx = info.get('max', '?')
                default = info.get('default', 0)
                val = input(f"  {col} [{mn} - {mx}] (default: {default}): ").strip()
                input_data[col] = float(val) if val else default
                
            elif ftype == 'categorical':
                options = info.get('options', [])
                print(f"  {col} options: {options}")
                val = input(f"  {col} (pick one): ").strip()
                input_data[col] = val if val else (options[0] if options else '')
                
            elif ftype == 'text':
                val = input(f"  {col} (enter text): ").strip()
                input_data[col] = val if val else ''
        result = predict_single(state, input_data)
    
    print(f"\n🎯 Prediction: {result['prediction']}")
    if 'confidence' in result:
        print(f"📊 Confidence: {result['confidence']:.1%}")
    if 'probabilities' in result:
        print(f"📊 Probabilities:")
        for cls, prob in sorted(result['probabilities'].items(), key=lambda x: x[1], reverse=True):
            bar = "█" * int(prob * 30)
            print(f"   {cls:>15}: {prob:.1%} {bar}")
    
    return result


def main():
    parser = argparse.ArgumentParser(description="Make predictions with your trained model")
    parser.add_argument('--model', type=str, default='model.pkl', help='Path to model file')
    parser.add_argument('--dl-model', type=str, default='deep_learning_model.pkl', help='Path to DL model file')
    parser.add_argument('--mode', type=str, default='auto', choices=['auto', 'traditional', 'dl'], help='Prediction mode')
    parser.add_argument('--json', type=str, default=None, help='JSON string with input data')
    parser.add_argument('--csv', type=str, default=None, help='CSV file for batch predictions')
    parser.add_argument('--output', type=str, default=None, help='Output CSV for batch predictions')
    parser.add_argument('--interactive', action='store_true', help='Interactive mode')
    args = parser.parse_args()
    
    # Auto-detect which model to use based on BEST_MODE from training
    use_dl = False
    dl_state = None
    state = None
    
    # Use DL if: explicitly requested, or BEST_MODE is deep_learning, or DL model exists
    if args.mode == 'dl' or (args.mode == 'auto' and BEST_MODE == 'deep_learning') or (args.mode == 'auto' and os.path.exists(args.dl_model) and not os.path.exists(args.model)):
        dl_state = load_dl_model(args.dl_model)
        if dl_state:
            use_dl = True
    
    if not use_dl:
        state = load_model(args.model)
        if state is None:
            # Last resort: try DL model
            dl_state = load_dl_model(args.dl_model)
            if dl_state:
                use_dl = True
            else:
                return
    
    if args.json:
        input_data = json.loads(args.json)
        if use_dl:
            result = predict_single_dl(dl_state, input_data)
        else:
            result = predict_single(state, input_data)
        print(f"\n🎯 Prediction: {result['prediction']}")
        if 'confidence' in result:
            print(f"📊 Confidence: {result['confidence']:.1%}")
        print(f"\n📋 Full result: {json.dumps(result, indent=2, default=str)}")
    elif args.csv:
        if use_dl:
            # Batch DL predictions
            df = pd.read_csv(args.csv)
            print(f"\n📊 Predicting for {len(df)} rows (DL mode)...")
            predictions = []
            for _, row in df.iterrows():
                result = predict_single_dl(dl_state, row.to_dict())
                predictions.append(result['prediction'])
            df['prediction'] = predictions
            output_path = args.output or args.csv.replace('.csv', '_predictions.csv')
            df.to_csv(output_path, index=False)
            print(f"💾 Predictions saved to: {output_path}")
        else:
            predict_batch(state, args.csv, args.output)
    else:
        interactive_mode(state, use_dl=use_dl)


# =========================================================================
# Example (using YOUR actual feature names):
#
# from predict import load_model, predict_single
# state = load_model('model.pkl')
# result = predict_single(state, {
#         'battery_power': 1238.51,  # numeric, range [510.0 .. 1987.0]
#         'blue': 0.49,  # numeric, range [0.0 .. 1.0]
#         'clock_speed': 1.52,  # numeric, range [0.5 .. 3.0]
#         'dual_sim': 0.51,  # numeric, range [0.0 .. 1.0]
#         'fc': 4.29,  # numeric, range [0.0 .. 16.0]
#         'four_g': 0.52,  # numeric, range [0.0 .. 1.0]
#         'int_memory': 32.05,  # numeric, range [2.0 .. 64.0]
#         'm_dep': 0.50,  # numeric, range [0.1 .. 1.0]
#         'mobile_wt': 140.24,  # numeric, range [80.0 .. 199.0]
#         'n_cores': 4.52,  # numeric, range [1.0 .. 8.0]
#         'pc': 9.92,  # numeric, range [0.0 .. 20.0]
#         'px_height': 644.46,  # numeric, range [15.0 .. 1791.01]
#         'ram': 2124.26,  # numeric, range [296.99 .. 3958.01]
#         'sc_h': 12.31,  # numeric, range [5.0 .. 19.0]
#         'sc_w': 5.76,  # numeric, range [0.0 .. 17.0]
#         'three_g': 1.00,  # numeric, range [1.0 .. 1.0]
#         'touch_screen': 0.50,  # numeric, range [0.0 .. 1.0]
#         'wifi': 0.51,  # numeric, range [0.0 .. 1.0]
# })
# print(result['prediction'])
# =========================================================================


if __name__ == '__main__':
    main()
