"""Sync DB with ORM models

Revision ID: 17f8ad287629
Revises: 806bb507a4b3
Create Date: 2026-07-12 18:43:42.378848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f8ad287629'
down_revision: Union[str, Sequence[str], None] = '806bb507a4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    if 'chat_channels' not in tables:
        op.create_table('chat_channels',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'webhooks' not in tables:
        op.create_table('webhooks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('secret', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
        sa.Column('failure_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'webhooks' not in tables:
        op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    if 'channel_messages' not in tables:
        op.create_table('channel_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_ai', sa.Boolean(), nullable=True),
        sa.Column('parent_id', sa.UUID(), nullable=True),
        sa.Column('is_pinned', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['channel_id'], ['chat_channels.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['channel_messages.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'channel_messages' not in tables:
        op.create_index(op.f('ix_channel_messages_user_id'), 'channel_messages', ['user_id'], unique=False)
    if 'channel_messages' not in tables:
        op.create_index(op.f('ix_channel_messages_parent_id'), 'channel_messages', ['parent_id'], unique=False)
    if 'channel_messages' not in tables:
        op.create_index(op.f('ix_channel_messages_channel_id'), 'channel_messages', ['channel_id'], unique=False)
    if 'dashboards' not in tables:
        op.create_table('dashboards',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'dashboards' not in tables:
        op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    if 'data_stories' not in tables:
        op.create_table('data_stories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('dataset_name', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'data_stories' not in tables:
        op.create_index(op.f('ix_data_stories_user_id'), 'data_stories', ['user_id'], unique=False)
    if 'developer_api_keys' not in tables:
        op.create_table('developer_api_keys',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('total_calls', sa.Integer(), nullable=True),
        sa.Column('data_processed_mb', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'developer_api_keys' not in tables:
        op.create_index(op.f('ix_developer_api_keys_user_id'), 'developer_api_keys', ['user_id'], unique=False)
    if 'developer_api_keys' not in tables:
        op.create_index(op.f('ix_developer_api_keys_api_key'), 'developer_api_keys', ['api_key'], unique=True)
    if 'ml_deployments' not in tables:
        op.create_table('ml_deployments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('deploy_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('task_type', sa.String(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('request_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_called_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ml_deployments' not in tables:
        op.create_index(op.f('ix_ml_deployments_user_id'), 'ml_deployments', ['user_id'], unique=False)
    if 'ml_deployments' not in tables:
        op.create_index(op.f('ix_ml_deployments_deploy_id'), 'ml_deployments', ['deploy_id'], unique=True)
    if 'ml_registry_models' not in tables:
        op.create_table('ml_registry_models',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('task_type', sa.String(), nullable=True),
        sa.Column('target_column', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ml_registry_models' not in tables:
        op.create_index(op.f('ix_ml_registry_models_user_id'), 'ml_registry_models', ['user_id'], unique=False)
    if 'ml_registry_models' not in tables:
        op.create_index(op.f('ix_ml_registry_models_name'), 'ml_registry_models', ['name'], unique=False)
    if 'visual_pipelines' not in tables:
        op.create_table('visual_pipelines',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_run_status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'visual_pipelines' not in tables:
        op.create_index(op.f('ix_visual_pipelines_user_id'), 'visual_pipelines', ['user_id'], unique=False)
    if 'charts' not in tables:
        op.create_table('charts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('dashboard_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('chart_type', sa.String(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'charts' not in tables:
        op.create_index(op.f('ix_charts_dashboard_id'), 'charts', ['dashboard_id'], unique=False)
    if 'ml_registry_versions' not in tables:
        op.create_table('ml_registry_versions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('model_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('algorithm', sa.String(), nullable=True),
        sa.Column('training_time_sec', sa.Float(), nullable=True),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('model_size_bytes', sa.BigInteger(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['ml_registry_models.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ml_registry_versions' not in tables:
        op.create_index(op.f('ix_ml_registry_versions_model_id'), 'ml_registry_versions', ['model_id'], unique=False)
    if 'mlops_deployments' not in tables:
        op.create_table('mlops_deployments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('deployment_type', sa.String(), nullable=True),
        sa.Column('champion_version_id', sa.UUID(), nullable=True),
        sa.Column('challenger_version_id', sa.UUID(), nullable=True),
        sa.Column('champion_traffic', sa.Integer(), nullable=True),
        sa.Column('challenger_traffic', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['challenger_version_id'], ['ml_registry_versions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['champion_version_id'], ['ml_registry_versions.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'mlops_deployments' not in tables:
        op.create_index(op.f('ix_mlops_deployments_user_id'), 'mlops_deployments', ['user_id'], unique=False)
    if 'mlops_experiments' not in tables:
        op.create_table('mlops_experiments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('deployment_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('primary_metric', sa.String(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('winner_version_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['deployment_id'], ['mlops_deployments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['winner_version_id'], ['ml_registry_versions.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'mlops_experiments' not in tables:
        op.create_index(op.f('ix_mlops_experiments_deployment_id'), 'mlops_experiments', ['deployment_id'], unique=False)
    if 'mlops_prediction_logs' not in tables:
        op.create_table('mlops_prediction_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('deployment_id', sa.UUID(), nullable=False),
        sa.Column('version_id', sa.UUID(), nullable=False),
        sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('latency_ms', sa.Float(), nullable=True),
        sa.Column('cpu_usage', sa.Float(), nullable=True),
        sa.Column('memory_mb', sa.Float(), nullable=True),
        sa.Column('is_shadow', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['deployment_id'], ['mlops_deployments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['version_id'], ['ml_registry_versions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'mlops_prediction_logs' not in tables:
        op.create_index(op.f('ix_mlops_prediction_logs_deployment_id'), 'mlops_prediction_logs', ['deployment_id'], unique=False)
    if 'mlops_prediction_logs' not in tables:
        op.create_index(op.f('ix_mlops_prediction_logs_created_at'), 'mlops_prediction_logs', ['created_at'], unique=False)

    if 'api_call_logs' not in tables:
        op.create_table('api_call_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('api_key_id', sa.UUID(), nullable=True),
        sa.Column('endpoint', sa.String(), nullable=False),
        sa.Column('method', sa.String(), nullable=False),
        sa.Column('status_code', sa.Integer(), nullable=False),
        sa.Column('latency_ms', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'api_call_logs' not in tables:
        op.create_index(op.f('ix_api_call_logs_api_key_id'), 'api_call_logs', ['api_key_id'], unique=False)
    if 'api_call_logs' not in tables:
        op.create_index(op.f('ix_api_call_logs_timestamp'), 'api_call_logs', ['timestamp'], unique=False)
    if 'api_call_logs' not in tables:
        op.create_index(op.f('ix_api_call_logs_user_id'), 'api_call_logs', ['user_id'], unique=False)
    if 'webhooks' not in tables:
        op.create_table('webhooks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('secret', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
        sa.Column('failure_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if 'webhooks' not in tables:
        op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    if 'activity_logs' not in tables:
        op.create_table('activity_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('detail', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'activity_logs' not in tables:
        op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    if 'activity_logs' not in tables:
        op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    if 'batch_prediction_jobs' not in tables:
        op.create_table('batch_prediction_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('input_filename', sa.String(), nullable=False),
        sa.Column('output_filename', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('total_rows', sa.Integer(), nullable=True),
        sa.Column('completed_rows', sa.Integer(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'batch_prediction_jobs' not in tables:
        op.create_index(op.f('ix_batch_prediction_jobs_user_id'), 'batch_prediction_jobs', ['user_id'], unique=False)
    if 'ml_experiments' not in tables:
        op.create_table('ml_experiments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('model_type', sa.String(), nullable=True),
        sa.Column('algorithm', sa.String(), nullable=True),
        sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('target_column', sa.String(), nullable=True),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_starred', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ml_experiments' not in tables:
        op.create_index(op.f('ix_ml_experiments_user_id'), 'ml_experiments', ['user_id'], unique=False)
    if 'notifications' not in tables:
        op.create_table('notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('workspace_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('channel', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'notifications' not in tables:
        op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    if 'notifications' not in tables:
        op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    if 'report_templates' not in tables:
        op.create_table('report_templates',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('report_type', sa.String(), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'report_templates' not in tables:
        op.create_index(op.f('ix_report_templates_user_id'), 'report_templates', ['user_id'], unique=False)
    if 'scheduled_reports' not in tables:
        op.create_table('scheduled_reports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('report_type', sa.String(), nullable=False),
        sa.Column('schedule_cron', sa.String(), nullable=False),
        sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('format', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_run_at', sa.DateTime(), nullable=True),
        sa.Column('next_run_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'scheduled_reports' not in tables:
        op.create_index(op.f('ix_scheduled_reports_user_id'), 'scheduled_reports', ['user_id'], unique=False)
    if 'webhook_endpoints' not in tables:
        op.create_table('webhook_endpoints',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('secret', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'webhook_endpoints' not in tables:
        op.create_index(op.f('ix_webhook_endpoints_user_id'), 'webhook_endpoints', ['user_id'], unique=False)
    if 'ab_test_configs' not in tables:
        op.create_table('ab_test_configs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('champion_experiment_id', sa.UUID(), nullable=True),
        sa.Column('challenger_experiment_id', sa.UUID(), nullable=True),
        sa.Column('champion_traffic', sa.Integer(), nullable=True),
        sa.Column('challenger_traffic', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('winner', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('ended_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['challenger_experiment_id'], ['ml_experiments.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['champion_experiment_id'], ['ml_experiments.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'ab_test_configs' not in tables:
        op.create_index(op.f('ix_ab_test_configs_user_id'), 'ab_test_configs', ['user_id'], unique=False)
    if 'deployed_models' not in tables:
        op.create_table('deployed_models',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('experiment_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('endpoint', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('traffic_split', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['experiment_id'], ['ml_experiments.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'deployed_models' not in tables:
        op.create_index(op.f('ix_deployed_models_user_id'), 'deployed_models', ['user_id'], unique=False)
    if 'message_reactions' not in tables:
        op.create_table('message_reactions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('message_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('emoji', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['channel_messages.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'message_reactions' not in tables:
        op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    if 'message_reactions' not in tables:
        op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    if 'report_history' not in tables:
        op.create_table('report_history',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('scheduled_report_id', sa.UUID(), nullable=True),
        sa.Column('report_type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('sections_count', sa.Integer(), nullable=True),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['scheduled_report_id'], ['scheduled_reports.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'report_history' not in tables:
        op.create_index(op.f('ix_report_history_generated_at'), 'report_history', ['generated_at'], unique=False)
    if 'report_history' not in tables:
        op.create_index(op.f('ix_report_history_user_id'), 'report_history', ['user_id'], unique=False)
    if 'webhook_deliveries' not in tables:
        op.create_table('webhook_deliveries',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('webhook_id', sa.UUID(), nullable=False),
        sa.Column('event', sa.String(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('status_code', sa.Integer(), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['webhook_id'], ['webhook_endpoints.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if 'webhook_deliveries' not in tables:
        op.create_index(op.f('ix_webhook_deliveries_timestamp'), 'webhook_deliveries', ['timestamp'], unique=False)
    if 'webhook_deliveries' not in tables:
        op.create_index(op.f('ix_webhook_deliveries_webhook_id'), 'webhook_deliveries', ['webhook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workspace_members', 'workspace_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_push_tokens_workspace_id'), table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_user_id'), table_name='push_tokens')
    op.alter_column('push_tokens', 'workspace_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('push_tokens', 'is_active')
    op.drop_column('developer_api_keys', 'expires_at')
    op.drop_column('developer_api_keys', 'scopes')
    op.drop_constraint(None, 'channel_messages', type_='foreignkey')
    op.drop_index(op.f('ix_channel_messages_parent_id'), table_name='channel_messages')
    op.drop_column('channel_messages', 'is_pinned')
    op.drop_column('channel_messages', 'parent_id')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_timestamp'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_report_history_user_id'), table_name='report_history')
    op.drop_index(op.f('ix_report_history_generated_at'), table_name='report_history')
    op.drop_table('report_history')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_deployed_models_user_id'), table_name='deployed_models')
    op.drop_table('deployed_models')
    op.drop_index(op.f('ix_ab_test_configs_user_id'), table_name='ab_test_configs')
    op.drop_table('ab_test_configs')
    op.drop_index(op.f('ix_webhook_endpoints_user_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_scheduled_reports_user_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_report_templates_user_id'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_ml_experiments_user_id'), table_name='ml_experiments')
    op.drop_table('ml_experiments')
    op.drop_index(op.f('ix_batch_prediction_jobs_user_id'), table_name='batch_prediction_jobs')
    op.drop_table('batch_prediction_jobs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_webhooks_user_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_api_call_logs_user_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_timestamp'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_api_key_id'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    # ### end Alembic commands ###
